import test from 'node:test';
import assert from 'node:assert/strict';
import {onRequestGet as listAgreements,onRequestPost as createAgreement} from '../functions/api/agreements/index.js';
import {onRequestGet as getAgreement,onRequestPatch as updateAgreement} from '../functions/api/agreements/[id].js';
import {reviewReadiness,agreementSummary} from '../functions/lib/agreements-compliance.js';

class FakeDB{constructor(resolver){this.resolver=resolver;this.calls=[]}prepare(sql){return{bind:(...bindings)=>{const call={sql:String(sql),bindings};this.calls.push(call);const index=this.calls.length-1;return{first:async()=>this.resolver('first',call,index),all:async()=>({results:await this.resolver('all',call,index)||[]}),run:async()=>this.resolver('run',call,index)||{success:true}}}}}}
const auth=(role='OWNER')=>({userId:'user_a',tenantId:'tenant_a',tenantSlug:'tenant-a',role,financeAccess:true});
function context({db,method='GET',body={},role='OWNER',id='agr_a'}={}){return{env:{DB:db,AUTH_MODE:'access'},data:{auth:auth(role)},params:{id},request:new Request(`https://crm.test/api/agreements/${id}`,{method,headers:{'content-type':'application/json'},body:['POST','PATCH'].includes(method)?JSON.stringify(body):undefined})}}
const payload=r=>r.json();
const row=(overrides={})=>({id:'agr_a',tenant_id:'tenant_a',project_id:'project_a',opportunity_id:null,campaign_id:null,partner_id:null,fundraising_round_id:null,agreement_type:'SERVICE_AGREEMENT',title:'AKARI Services Agreement',counterparty_name:'Project A',owner_user_id:'user_a',owner_name:'Owner',project_name:'Project A',status:'REVIEW',jurisdiction:'Germany',governing_law_note:null,scope_summary:'GTM services',currency:'USD',retainer_amount:1000,success_fee_percentage:0,success_fee_note:null,exclusivity:'NON_EXCLUSIVE',confidentiality_required:1,conflict_review_required:0,privacy_review_required:0,compliance_review_required:0,start_date:'2026-08-01',end_date:'2027-07-31',renewal_date:'2027-06-30',sent_at:null,signed_at:null,signed_by_name:null,signature_method:null,signed_document_url:null,signature_evidence_reference:null,activated_at:null,terminated_at:null,termination_reason:null,notes:null,...overrides});
const reviews=(status='NOT_STARTED')=>[{id:'review_commercial',tenant_id:'tenant_a',agreement_id:'agr_a',review_type:'COMMERCIAL',status,reviewer_user_id:null,decision_note:status==='CLEAR'?'Commercial terms reviewed and cleared.':null,evidence_reference:null,reviewed_at:status==='CLEAR'?'2026-08-12T10:00:00Z':null}];
function itemDb(agreement=row(),reviewRows=reviews()){return new FakeDB((method,call)=>{if(method==='first'&&/sqlite_master/.test(call.sql))return{name:'agreements'};if(method==='first'&&/FROM agreements a/.test(call.sql))return agreement;if(method==='all'&&/FROM agreement_reviews r/.test(call.sql))return reviewRows;if(method==='first'&&/tenant_memberships/.test(call.sql))return{user_id:'user_a'};return null})}

test('R70 agreement lookup cannot resolve another tenant agreement',async()=>{const db=new FakeDB((method,call)=>{if(method==='first'&&/sqlite_master/.test(call.sql))return{name:'agreements'};if(method==='first'&&/FROM agreements a/.test(call.sql))return null;return null});const response=await getAgreement(context({db,id:'agr_other'}));assert.equal(response.status,404);const lookup=db.calls.find(c=>/FROM agreements a/.test(c.sql));assert.deepEqual(lookup.bindings,['tenant_a','agr_other']);assert.match(lookup.sql,/a\.tenant_id=\? AND a\.id=\?/)});

test('R70 BD Member cannot create agreement records before database access',async()=>{const db=new FakeDB(()=>{throw new Error('database should not be reached')});const response=await createAgreement(context({db,method:'POST',role:'BD_MEMBER',body:{agreementType:'SERVICE_AGREEMENT',projectId:'project_a',title:'Service Agreement',counterpartyName:'Project A'}}));assert.equal(response.status,403);assert.equal(db.calls.length,0)});

test('R70 agreement creation rejects an opportunity outside the selected tenant project',async()=>{const db=new FakeDB((method,call)=>{if(method==='first'&&/sqlite_master/.test(call.sql))return{name:'agreements'};if(method==='first'&&/FROM projects/.test(call.sql))return{id:'project_a',name:'Project A'};if(method==='first'&&/FROM opportunities/.test(call.sql))return null;return null});const response=await createAgreement(context({db,method:'POST',role:'BD_MANAGER',body:{agreementType:'SERVICE_AGREEMENT',projectId:'project_a',opportunityId:'opp_other',title:'Service Agreement',counterpartyName:'Project A'}}));assert.equal(response.status,422);assert.match((await payload(response)).error,/Opportunity does not belong/i);assert.equal(db.calls.some(c=>/INSERT INTO agreements/.test(c.sql)),false);const oppLookup=db.calls.find(c=>/FROM opportunities/.test(c.sql));assert.deepEqual(oppLookup.bindings,['tenant_a','opp_other','project_a'])});

test('R70 agreement approval fails closed while a required review is pending',async()=>{const db=itemDb(row({status:'REVIEW'}),reviews('NOT_STARTED'));const response=await updateAgreement(context({db,method:'PATCH',role:'OWNER',body:{action:'APPROVE'}}));assert.equal(response.status,409);assert.match((await payload(response)).error,/required reviews are clear or not required/i);assert.equal(db.calls.some(c=>/SET status='APPROVED'/.test(c.sql)),false)});

test('R70 final review decisions remain Owner or Admin controlled',async()=>{const db=itemDb(row({status:'REVIEW'}),reviews('IN_REVIEW'));const response=await updateAgreement(context({db,method:'PATCH',role:'BD_MANAGER',body:{action:'REVIEW_UPDATE',reviewType:'COMMERCIAL',status:'CLEAR',decisionNote:'Commercial terms reviewed and cleared.'}}));assert.equal(response.status,403);assert.match((await payload(response)).error,/Owner or Admin/i);assert.equal(db.calls.some(c=>/INSERT INTO agreement_reviews/.test(c.sql)),false)});

test('R70 sent agreement cannot be recorded as signed without signature evidence',async()=>{const db=itemDb(row({status:'SENT'}),reviews('CLEAR'));const response=await updateAgreement(context({db,method:'PATCH',role:'BD_MANAGER',body:{action:'RECORD_SIGNED',signedByName:'Founder',signedAt:'2026-08-12T20:00:00Z'}}));assert.equal(response.status,422);assert.match((await payload(response)).error,/signed document or signature evidence/i);assert.equal(db.calls.some(c=>/SET status='SIGNED'/.test(c.sql)),false)});

test('R70 activation fails closed when a signed agreement has blocked governance evidence',async()=>{const blocked=[{...reviews('CLEAR')[0],review_type:'JURISDICTION',status:'BLOCKED',decision_note:'Jurisdiction review identified a blocking issue.'}];const agreement=row({status:'SIGNED',retainer_amount:0,agreement_type:'FUNDRAISING_MANDATE',conflict_review_required:0,privacy_review_required:0,compliance_review_required:0});const db=itemDb(agreement,blocked);const response=await updateAgreement(context({db,method:'PATCH',role:'OWNER',body:{action:'ACTIVATE'}}));assert.equal(response.status,409);assert.match((await payload(response)).error,/required reviews are clear or not required/i);assert.equal(db.calls.some(c=>/SET status='ACTIVE'/.test(c.sql)),false)});

test('R70 readiness explicitly distinguishes blocked and upcoming renewal attention',()=>{const agreement=row({status:'ACTIVE',retainer_amount:0,end_date:'2026-09-05',renewal_date:'2026-08-25',conflict_review_required:1});const clear=[{review_type:'JURISDICTION',status:'CLEAR'},{review_type:'CONFLICT',status:'CLEAR'}];const readiness=reviewReadiness(agreement,clear);assert.equal(readiness.ready,true);const summary=agreementSummary(agreement,clear,'2026-08-12');assert.equal(summary.renewalDueSoon,true);assert.equal(summary.attention,'DUE_SOON')});
