import test from 'node:test';
import assert from 'node:assert/strict';
import {onRequestGet,onRequestPatch} from '../functions/api/campaign-closeout/[id].js';
import {campaignCloseoutFingerprint,buildCampaignCloseoutSummary} from '../functions/lib/campaign-closeout-renewal.js';

class FakeDB{constructor(resolver){this.resolver=resolver;this.calls=[]}prepare(sql){return{bind:(...bindings)=>{const call={sql:String(sql),bindings};this.calls.push(call);const index=this.calls.length-1;return{first:async()=>this.resolver('first',call,index),all:async()=>({results:await this.resolver('all',call,index)||[]}),run:async()=>this.resolver('run',call,index)||{success:true}}}}}}
const tracking={version:3,overview:{},targets:[],socialUpdates:[],creatorAssignments:[],creatorPosts:[]};
const gtm={version:2,activities:[]};
const planning={status:'DRAFT',objective:'BALANCED',platform:'ALL',creatorType:'ALL',contentType:'ALL',region:'ALL',budgetUsd:0,selections:[],compensation:{enabled:false}};
const activation={status:'COMPLETED',completedAt:'2026-08-12T10:00:00Z'};
const settlement={records:[],payments:[]};
function notes(closeout={}){const fp=campaignCloseoutFingerprint(tracking,gtm,planning,activation,settlement);return JSON.stringify({campaignTracking:tracking,campaignGtmTracking:gtm,campaignPlanning:planning,campaignActivation:activation,campaignSettlement:settlement,campaignCloseout:{status:'SENT_TO_CLIENT',reportFingerprint:fp,clientSentAt:'2026-08-12T11:00:00Z',clientSentReference:'client-email-thread-1',clientSentChannel:'Email',renewalRecommendation:'RENEW',renewalReason:'Continue into a second campaign',renewalTargetDate:'2026-09-15',...closeout}})}
function campaign(customNotes=notes()){return{id:'cam_a',name:'Launch Campaign',status:'REPORTING',region:'Global',start_date:'2026-08-01',end_date:'2026-08-31',notes:customNotes,project_id:'project_a',campaign_owner_id:'user_a',project_name:'Project A'}}
function context({db,method='PATCH',body={action:'COMPLETE_CLOSEOUT',note:'Client report accepted and campaign closed.'},role='OWNER',id='cam_a'}={}){return{env:{DB:db,AUTH_MODE:'access'},data:{auth:{userId:'user_a',tenantId:'tenant_a',tenantSlug:'tenant-a',role,financeAccess:true}},params:{id},request:new Request(`https://crm.test/api/campaign-closeout/${id}`,{method,headers:{'content-type':'application/json'},body:method==='PATCH'?JSON.stringify(body):undefined})}}
const payload=r=>r.json();

test('R69 campaign closeout lookup cannot resolve another tenant campaign',async()=>{const db=new FakeDB((method,call)=>method==='first'&&/FROM campaigns c/.test(call.sql)?null:[]);const response=await onRequestGet(context({db,method:'GET',id:'cam_other'}));assert.equal(response.status,404);const lookup=db.calls.find(c=>/FROM campaigns c/.test(c.sql));assert.deepEqual(lookup.bindings,['tenant_a','cam_other']);assert.match(lookup.sql,/c\.tenant_id=\? AND c\.id=\?/)});

test('R69 manager-only report approval stays tenant scoped',async()=>{const db=new FakeDB((method,call)=>method==='first'&&/FROM campaigns c/.test(call.sql)?campaign(notes({status:'READY_FOR_APPROVAL'})):null);const response=await onRequestPatch(context({db,role:'BD_MEMBER',body:{action:'APPROVE_REPORT'}}));assert.equal(response.status,403);assert.match((await payload(response)).error,/Owner, Admin or BD Manager/i);const lookup=db.calls.find(c=>/FROM campaigns c/.test(c.sql));assert.deepEqual(lookup.bindings,['tenant_a','cam_a']);assert.equal(db.calls.some(c=>/UPDATE campaigns/.test(c.sql)),false)});

test('R69 settlement coverage fails closed when USDT was planned but no paid settlement exists',()=>{const paidTracking={...tracking,creatorAssignments:[{id:'cca_1',creatorType:'CREATOR',name:'Alice',platform:'X',expectedPosts:1,expectedReach:1000,active:true}],creatorPosts:[{id:'post_1',assignmentId:'cca_1',status:'APPROVED',reach:1000,totalEngagements:100}]};const paidPlanning={...planning,status:'APPROVED',compensation:{enabled:true,budgetUsdt:100,bonusPoolUsdt:0,maximumBaseAllocationUsdt:100,maximumBonusPerTalentUsdt:0,lastResult:{items:[{assignmentId:'cca_1',payoutUsdt:100}]}}};const summary=buildCampaignCloseoutSummary(paidTracking,gtm,paidPlanning,activation,{records:[],payments:[]},{status:'SENT_TO_CLIENT',reportFingerprint:'old',clientSentAt:'2026-08-12',clientSentReference:'email',renewalRecommendation:'RENEW'});assert.equal(summary.settlementRequiredTalentCount,1);assert.equal(summary.settlementPaidTalentCount,0);assert.equal(summary.settlementCoverageComplete,false);assert.equal(summary.settlementClear,false)});

test('R69 completion creates one canonical tenant-scoped renewal opportunity and links it to closeout',async()=>{const db=new FakeDB((method,call)=>{if(method==='first'&&/FROM campaigns c/.test(call.sql))return campaign();if(method==='first'&&/FROM opportunities/.test(call.sql))return null;return null});const response=await onRequestPatch(context({db}));assert.equal(response.status,200);const body=await payload(response);assert.equal(body.item.closeout.status,'COMPLETED');assert.equal(body.item.campaignStatus,'COMPLETED');assert.ok(body.item.closeout.renewalOpportunityId);const opportunityWrite=db.calls.find(c=>/INSERT INTO opportunities/.test(c.sql));assert.equal(opportunityWrite.bindings[1],'tenant_a');assert.equal(opportunityWrite.bindings[2],'project_a');assert.match(opportunityWrite.bindings[5],/^\[AKARI_CAMPAIGN_RENEWAL:cam_a\]/);const campaignWrite=db.calls.find(c=>/UPDATE campaigns SET notes/.test(c.sql));assert.equal(campaignWrite.bindings.at(-2),'tenant_a');assert.equal(campaignWrite.bindings.at(-1),'cam_a')});

test('R69 completion reuses the existing campaign renewal opportunity on retry',async()=>{const db=new FakeDB((method,call)=>{if(method==='first'&&/FROM campaigns c/.test(call.sql))return campaign();if(method==='first'&&/FROM opportunities/.test(call.sql))return{id:'opp_existing',name:'Project A — Renewal'};return null});const response=await onRequestPatch(context({db}));assert.equal(response.status,200);const body=await payload(response);assert.equal(body.item.closeout.renewalOpportunityId,'opp_existing');assert.equal(db.calls.some(c=>/INSERT INTO opportunities/.test(c.sql)),false);const duplicateLookup=db.calls.find(c=>/FROM opportunities/.test(c.sql));assert.deepEqual(duplicateLookup.bindings,['tenant_a','project_a','[AKARI_CAMPAIGN_RENEWAL:cam_a]%'])});
