import { test, expect } from '@playwright/test';

function commandPayload(scope='team'){
  const drift={id:'cam_drift',name:'Drift Campaign',projectId:'prj_1',projectName:'Project One',ownerUserId:'usr_owner',ownerName:'Muaz Test',campaignStatus:'LIVE',startDate:'2026-08-01',endDate:'2026-08-20',region:'EMEA',active:true,planning:{status:'APPROVED',approvalDrift:true,budgetUsd:500,estimatedPlanCost:300,budgetReconciled:true,budgetUtilization:60},outreach:{talentCount:2,confirmedCount:2,pendingCount:0,declinedCount:0,readyForActivation:true},activation:{status:'ACTIVE',effectiveStatus:'CHANGES_AFTER_ACTIVATION',activationDrift:true,outreachDrift:false},delivery:{plannedPosts:4,approvedPosts:2,holdingPosts:0,rejectedPosts:0,remainingPosts:2,postCompletionPercent:50,approvedReach:12000,approvedEngagements:900,expectedReach:20000,reachAchievement:60},tasks:{total:3,open:2,done:1,overdue:0,dueToday:0,blocked:0,overdueItems:[]},settlement:{outstandingUsdt:0,disputedCount:0,paidUsdt:0},pacing:{elapsedPercent:45,daysToStart:-8,daysToEnd:11,ended:false,started:true},risk:{level:'CRITICAL',score:90,reasons:[{code:'PLAN_APPROVAL_DRIFT',label:'Approved plan changed',points:45},{code:'ACTIVATION_PLAN_DRIFT',label:'Approved plan changed after activation',points:45}]},nextAction:{code:'RECONCILE_PLAN',label:'Reconcile approved campaign plan',detail:'The approved plan changed. Reconcile the basket/economics and reapprove before execution continues.',route:'CAMPAIGNS'}};
  const overdue={id:'cam_overdue',name:'Overdue Campaign',projectId:'prj_2',projectName:'Project Two',ownerUserId:'usr_owner',ownerName:'Muaz Test',campaignStatus:'LIVE',startDate:'2026-08-01',endDate:'2026-08-20',region:'APAC',active:true,planning:{status:'APPROVED',approvalDrift:false,budgetUsd:400,estimatedPlanCost:250,budgetReconciled:true,budgetUtilization:62.5},outreach:{talentCount:1,confirmedCount:1,pendingCount:0,declinedCount:0,readyForActivation:true},activation:{status:'ACTIVE',effectiveStatus:'ACTIVE',activationDrift:false,outreachDrift:false},delivery:{plannedPosts:2,approvedPosts:1,holdingPosts:0,rejectedPosts:0,remainingPosts:1,postCompletionPercent:50,approvedReach:5000,approvedEngagements:300,expectedReach:10000,reachAchievement:50},tasks:{total:2,open:1,done:1,overdue:1,dueToday:0,blocked:0,overdueItems:[{id:'tsk_2',title:'Approve Creator draft',status:'TODO',priority:'HIGH',dueAt:'2026-08-08',ownerName:'Muaz Test'}]},settlement:{outstandingUsdt:0,disputedCount:0,paidUsdt:0},pacing:{elapsedPercent:45,daysToStart:-8,daysToEnd:11,ended:false,started:true},risk:{level:'MEDIUM',score:18,reasons:[{code:'OVERDUE_TASKS',label:'1 Work OS task overdue',points:18}]},nextAction:{code:'RESOLVE_OVERDUE_TASKS',label:'Resolve overdue Work OS tasks',detail:'1 open campaign task is overdue.',route:'TASKS'}};
  const items=scope==='mine'?[drift,overdue]:[drift,overdue];
  return {command:{version:'R8.5L-1',today:'2026-08-09',scope:scope==='mine'?'MINE':'TEAM',metrics:{campaigns:2,activeCampaigns:2,critical:1,highRisk:0,overdueTasks:1,dueTodayTasks:0,blockedTasks:0,pendingTalent:0,declinedTalent:0,holdingPosts:0,rejectedPosts:0,plannedPosts:6,approvedPosts:3,approvedReach:17000,outstandingSettlementUsdt:0},attention:items,items},permissions:{canManage:true,canOperate:true},methodology:{version:'R8.5L-1',tenantScoped:true,approvedOnlyPerformance:true,canonicalWorkOsTasks:true,singleRankedNextAction:true,financialAllocationIsNotPayment:true}};
}

function responseFor(url){
  const parsed=new URL(url);
  if(parsed.pathname==='/api/me')return {user:{userId:'usr_owner',tenantId:'tenant_a',tenantSlug:'akari-house',email:'owner@example.com',fullName:'Muaz Test',role:'OWNER',financeAccess:true}};
  if(parsed.pathname==='/api/dashboard')return {currency:'USD',metrics:{monthlyTarget:0,revenueBooked:0,revenueCollected:0,netRevenue:0,weightedPipeline:0,activeOpportunities:0,yearToDateRevenue:0,activeCustomers:0,activeCampaigns:2,activePartners:0,outstandingPayments:0,referralRewardsDue:0}};
  if(parsed.pathname==='/api/campaign-execution-command-center')return commandPayload(parsed.searchParams.get('scope')||'team');
  if(parsed.pathname==='/api/campaigns')return {items:[{id:'cam_drift',project_id:'prj_1',name:'Drift Campaign',project_name:'Project One',status:'LIVE',region:'EMEA',start_date:'2026-08-01',end_date:'2026-08-20',currency:'USD'},{id:'cam_overdue',project_id:'prj_2',name:'Overdue Campaign',project_name:'Project Two',status:'LIVE',region:'APAC',start_date:'2026-08-01',end_date:'2026-08-20',currency:'USD'}],total:2};
  if(parsed.pathname==='/api/tasks')return {items:[{id:'tsk_2',title:'Approve Creator draft',status:'TODO',priority:'HIGH',due_at:'2026-08-08',campaign_id:'cam_overdue'}],total:1};
  if(parsed.pathname==='/api/opportunities')return {items:[],total:0};
  if(parsed.pathname==='/api/akari-leads')return {items:[],total:0,categories:[],canWrite:true};
  if(parsed.pathname==='/api/service-delivery')return {metrics:{},items:[],total:0,financeVisible:true};
  if(parsed.pathname==='/api/creator-directory')return {directory:{sourceAvailable:true,sourceWarning:null,creatorCount:0,withCrmHistory:0,withPerformanceEvidence:0,plannedWithoutPerformance:0,newToCrm:0,externalUnlinkedCount:0,items:[],external:[]},methodology:{}};
  if(parsed.pathname==='/api/campaign-talent-recommendations')return {intelligence:{criteria:{objective:'BALANCED',platform:'ALL',creatorType:'ALL',contentType:'ALL',region:'ALL',budgetUsd:0},eligibleCount:0,recommendations:[],basket:{budgetUsd:0,items:[]},partnerRecommendations:[],insights:{underusedReliable:[],spendWithoutDelivery:[],mostUsed:[]},facets:{objectives:['BALANCED'],creatorTypes:['ALL'],platforms:['ALL'],contentTypes:['ALL'],regions:['ALL']},methodology:{approvedOnly:true,deterministic:true,rankingVersion:'R8.5E-1'}}};
  if(parsed.pathname==='/api/creator-kol-intelligence')return {portfolio:{contributorCount:0,activeContributors:0,creators:0,kols:0,totalApprovedPosts:0,totalApprovedReach:0,totalTrackedAllocationValue:0,needsAttention:0,lowConfidenceIdentities:0,items:[]}};
  if(parsed.pathname==='/api/delivery-partner-intelligence')return {portfolio:{partnerCount:0,partnersWithCampaignHistory:0,activePartners:0,totalApprovedPosts:0,totalApprovedReach:0,totalCampaignCost:0,needsAttention:0,legacyUnmappedAssignments:0,items:[]}};
  if(parsed.pathname.startsWith('/api/campaign-planning/'))return {item:{id:'cam_drift',name:'Drift Campaign',projectId:'prj_1',projectName:'Project One',status:'LIVE',region:'EMEA',startDate:'2026-08-01',endDate:'2026-08-20',overview:{currentTokenPrice:0},planning:{status:'APPROVED',objective:'BALANCED',platform:'X',creatorType:'ALL',contentType:'Post',region:'EMEA',budgetUsd:500,notes:'',selections:[]},summary:{status:'APPROVED',effectiveStatus:'CHANGES_AFTER_APPROVAL',approvalDrift:true,currentFingerprint:'fp_new',approvedFingerprint:'fp_old',talentCount:0,creatorCount:0,kolCount:0,partnerCount:0,plannedPosts:0,plannedReach:0,cashAllocation:0,tokenAllocation:0,tokenPrice:0,estimatedTokenValue:0,reservedBonusPoolUsd:0,estimatedPlanCost:0,budgetUsd:500,remainingBudget:500,budgetUtilization:0,budgetReconciled:true,compensationEnabled:false,compensationCalculationCurrent:true},planItems:[]},recommendations:{criteria:{objective:'BALANCED',platform:'X',creatorType:'ALL',contentType:'Post',region:'EMEA',budgetUsd:500},eligibleCount:0,recommendations:[],partnerRecommendations:[],insights:{underusedReliable:[],spendWithoutDelivery:[],mostUsed:[]},facets:{objectives:['BALANCED'],creatorTypes:['ALL'],platforms:['ALL','X'],contentTypes:['ALL','Post'],regions:['ALL','EMEA']},methodology:{approvedOnly:true,deterministic:true,rankingVersion:'R8.5E-1'}},deliveryPartners:[],permissions:{canWrite:true,canManage:true}};
  if(parsed.pathname.startsWith('/api/campaign-compensation/'))return {item:{id:'cam_drift',name:'Drift Campaign',planningStatus:'APPROVED',planningBudgetUsd:500,compensation:{enabled:false},summary:{enabled:false,currency:'USDT',activeTalentCount:0,includedTalentCount:0,verifiedTalentCount:0,unsupportedTalentCount:0,budgetUsdt:0,baseBudgetUsdt:0,bonusPoolUsdt:0,maximumBaseAllocationUsdt:0,maximumBonusPerTalentUsdt:0,calculatedBaseAllocationUsdt:0,unallocatedBaseUsdt:0,calculationCurrent:true,currentFingerprint:'fp',lastAppliedFingerprint:null,calculationError:null,calculation:{items:[]}},planSummary:{estimatedPlanCost:0,remainingBudget:500},talent:[]},permissions:{canWrite:true,canManage:true}};
  if(parsed.pathname.startsWith('/api/campaign-talent-outreach/'))return {item:{id:'cam_drift',name:'Drift Campaign',planningStatus:'APPROVED',planSummary:{approvalDrift:true,budgetReconciled:true,compensationCalculationCurrent:true},summary:{talentCount:0,confirmedCount:0,contactedCount:0,negotiatingCount:0,acceptedCount:0,declinedCount:0,commercialMismatchCount:0,pendingCount:0,readyForActivation:false},talent:[]},members:[],permissions:{canWrite:true,canConfirm:true}};
  if(parsed.pathname.startsWith('/api/campaign-settlement/'))return {item:{id:'cam_drift',name:'Drift Campaign',planningStatus:'APPROVED',summary:{governanceReady:false,bonusPoolUsdt:0,maximumBonusPerTalentUsdt:0,talentCount:0,baseReadyCount:0,bonusEligibleCount:0,recommendedBonusUsdt:0,approvedBaseUsdt:0,approvedBonusUsdt:0,paidUsdt:0,outstandingUsdt:0,disputedCount:0,driftCount:0,paidCount:0},talent:[]},permissions:{canManage:true,canFinance:true,canApprove:true,canVoid:true}};
  if(parsed.pathname.startsWith('/api/campaign-activation/'))return {item:{id:'cam_drift',name:'Drift Campaign',planningStatus:'APPROVED',activation:{status:'ACTIVE',taskIds:[],taskPlan:[]},summary:{effectiveStatus:'CHANGES_AFTER_ACTIVATION',governanceReady:false,activationDrift:true,outreachDrift:false,talentCount:0,confirmedTalentCount:0,plannedPosts:0,approvedPosts:0,approvedReach:0,approvedEngagements:0,taskCount:0,taskDoneCount:0,taskOpenCount:0,taskCompletionPercent:0,deliveryCompletionPercent:0,completionReady:false},tasks:[]},members:[],permissions:{canManage:true}};
  return {items:[],total:0};
}

test.beforeEach(async({page})=>{
  await page.clock.setFixedTime(new Date('2026-08-09T12:00:00.000Z'));
  await page.route('**/api/**',async(route)=>{await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(responseFor(route.request().url()))});});
  await page.goto('http://127.0.0.1:4173/app/akari-house/home');
  await expect(page.getByRole('heading',{name:/Good (morning|afternoon|evening), Muaz/i})).toBeVisible();
});

test('Campaign Execution Command Centre ranks governance drift first and hands overdue work to canonical Tasks',async({page})=>{
  await page.locator('.sidebar [data-route="campaigns"]').click();
  await expect(page.getByRole('heading',{name:'Campaigns'})).toBeVisible();
  const panel=page.locator('.campaign-execution-command-r62');
  await expect(panel).toBeVisible();
  await expect(panel.getByText('Execution Command Centre',{exact:true})).toBeVisible();
  const attention=panel.locator('.campaign-execution-attention-list-r62 article');
  await expect(attention).toHaveCount(2);
  await expect(attention.nth(0).getByText('Drift Campaign',{exact:true})).toBeVisible();
  await expect(attention.nth(0).getByText('Critical',{exact:false})).toBeVisible();
  await expect(attention.nth(0).getByRole('button',{name:'Reconcile approved campaign plan',exact:true})).toBeVisible();
  await expect(attention.nth(1).getByText('Overdue Campaign',{exact:true})).toBeVisible();
  await expect(panel.getByText('17,000',{exact:true}).first()).toBeVisible();

  const overdueRow=panel.locator('[data-command-row="cam_overdue"]');
  await expect(overdueRow.getByText('1 overdue',{exact:true})).toBeVisible();
  await overdueRow.getByRole('button',{name:'Resolve overdue Work OS tasks'}).click();
  await expect(page).toHaveURL(/\/app\/akari-house\/tasks/);
});
