import test from 'node:test';
import assert from 'node:assert/strict';
import { onRequestGet as portalHome } from '../functions/api/portal/index.js';
import { onRequestGet as portalProject, onRequestPatch as updatePortalProject } from '../functions/api/portal/project/[id].js';
import { onRequestGet as portalAdmin, onRequestPost as updatePortalAdmin } from '../functions/api/portal-admin/index.js';

class FakeDB {
  constructor(resolver){this.resolver=resolver;this.calls=[];}
  prepare(sql){return{bind:(...bindings)=>{const call={sql:String(sql),bindings};this.calls.push(call);return{first:async()=>this.resolver('first',call,this.calls.length-1),all:async()=>({results:await this.resolver('all',call,this.calls.length-1)||[]}),run:async()=>this.resolver('run',call,this.calls.length-1)||{success:true}}}};}
}
function ctx({db,path,method='GET',body={},role='EXTERNAL_COLLABORATOR',userId='external_a',params={}}){return{env:{DB:db,AUTH_MODE:'access'},data:{auth:{userId,tenantId:'tenant_a',tenantSlug:'tenant-a',tenantName:'Tenant A',email:`${userId}@example.test`,fullName:'External User',role,financeAccess:false}},params,request:new Request(`https://crm.example.test${path}`,{method,headers:{'content-type':'application/json'},body:method==='GET'?undefined:JSON.stringify(body)})};}
const responseBody=response=>response.json();
const activeGrant=(overrides={})=>({recordType:'AKARI_EXTERNAL_PORTAL_ACCESS_V1',version:1,userId:'external_a',projectId:'project_a',portalType:'FOUNDER',status:'ACTIVE',permissions:{viewEngagement:true,viewCampaigns:true,viewFundraising:true,viewDocuments:true,viewReports:true,updateOwnTasks:true,answerDiligence:true},updatedAt:'2026-08-11T00:00:00.000Z',updatedBy:'owner_a',...overrides});
const grantRow=grant=>({id:'act_grant',user_id:'owner_a',project_id:grant.projectId,description:JSON.stringify(grant),occurred_at:'2026-08-11T00:00:00.000Z',created_at:'2026-08-11T00:00:00.000Z'});
const project={id:'project_a',name:'FounderCo',category:'Web3',region:'Europe',country:'Germany',website:'https://founder.example',lifecycle_status:'CLIENT'};

test('portal administration is Owner/Admin only and fails before database access',async()=>{const db=new FakeDB(()=>null);const response=await portalAdmin(ctx({db,path:'/api/portal-admin',role:'BD_MANAGER',userId:'manager_a'}));assert.equal(response.status,403);assert.equal(db.calls.length,0);assert.match((await responseBody(response)).error,/permission/i);});

test('portal home returns only explicitly granted tenant projects',async()=>{const grant=activeGrant();const db=new FakeDB((method,call)=>{if(method==='all'&&/FROM activities/i.test(call.sql))return[grantRow(grant)];if(method==='all'&&/FROM projects/i.test(call.sql))return[project];return null;});const response=await portalHome(ctx({db,path:'/api/portal'}));const payload=await responseBody(response);assert.equal(response.status,200);assert.equal(payload.projects.length,1);assert.equal(payload.projects[0].id,'project_a');const projectCall=db.calls.find(call=>/FROM projects/i.test(call.sql));assert.deepEqual(projectCall.bindings,['tenant_a','project_a']);assert.equal(payload.security.explicitProjectGrants,true);});

test('external collaborator cannot open an ungranted or revoked project',async()=>{for(const rows of [[],[grantRow(activeGrant({status:'REVOKED'}))]]){const db=new FakeDB((method,call)=>{if(method==='first'&&/FROM projects/i.test(call.sql))return{...project,id:'project_b'};if(method==='all'&&/FROM activities/i.test(call.sql))return rows;return null;});const response=await portalProject(ctx({db,path:'/api/portal/project/project_b',params:{id:'project_b'}}));assert.equal(response.status,403);assert.match((await responseBody(response)).error,/do not have portal access/i);assert.deepEqual(db.calls[0].bindings,['tenant_a','project_b']);}});

test('portal project read is scoped to granted project and external user task ownership',async()=>{const grant=activeGrant();const db=new FakeDB((method,call)=>{if(method==='first'&&/FROM projects/i.test(call.sql))return project;if(method==='all'&&/FROM activities/i.test(call.sql))return[grantRow(grant)];if(method==='all'&&/FROM tasks/i.test(call.sql))return[{id:'task_a',title:'Upload updated deck',description:'Founder action',status:'TODO',priority:'HIGH',due_at:'2026-08-20',completed_at:null}];if(method==='all'&&/FROM campaigns/i.test(call.sql))return[{id:'campaign_a',name:'Launch',status:'ACTIVE',start_date:'2026-08-01',end_date:'2026-08-31',region:'Global',tracking_enabled:1}];if(method==='first'&&/tenant_settings/i.test(call.sql))return{feature_flags_json:JSON.stringify({fundraisingCapitalRooms:[]})};return null;});const response=await portalProject(ctx({db,path:'/api/portal/project/project_a',params:{id:'project_a'}}));const payload=await responseBody(response);assert.equal(response.status,200);assert.equal(payload.tasks.length,1);assert.equal(payload.campaigns.length,1);const taskCall=db.calls.find(call=>/FROM tasks/i.test(call.sql));assert.deepEqual(taskCall.bindings,['tenant_a','project_a','external_a']);assert.equal(payload.disclosures.financeExcluded,true);assert.equal(JSON.stringify(payload).includes('payment'),false);});

test('portal task update requires tenant, granted project, task id and external owner',async()=>{const grant=activeGrant();const db=new FakeDB((method,call)=>{if(method==='first'&&/FROM projects/i.test(call.sql))return project;if(method==='all'&&/FROM activities/i.test(call.sql))return[grantRow(grant)];if(method==='first'&&/SELECT id,status FROM tasks/i.test(call.sql))return{id:'task_a',status:'TODO'};if(method==='run')return{success:true};if(method==='all'&&/FROM tasks/i.test(call.sql))return[];if(method==='all'&&/FROM campaigns/i.test(call.sql))return[];if(method==='first'&&/tenant_settings/i.test(call.sql))return{feature_flags_json:'{}'};return null;});const response=await updatePortalProject(ctx({db,path:'/api/portal/project/project_a',method:'PATCH',params:{id:'project_a'},body:{action:'UPDATE_TASK',taskId:'task_a',status:'DONE'}}));assert.equal(response.status,200);const update=db.calls.find(call=>/UPDATE tasks SET/i.test(call.sql));assert.ok(update);assert.deepEqual(update.bindings.slice(-4),['tenant_a','project_a','task_a','external_a']);assert.match(update.sql,/tenant_id=\?.*project_id=\?.*id=\?.*owner_user_id=\?/s);});

test('portal grant audit keeps administrator actor separate from external subject',async()=>{const db=new FakeDB((method,call)=>{if(method==='first'&&/tenant_memberships/i.test(call.sql))return{user_id:'external_a',full_name:'Founder A',email:'founder@example.test'};if(method==='first'&&/FROM projects/i.test(call.sql))return{id:'project_a',name:'FounderCo'};if(method==='all'&&/FROM activities/i.test(call.sql))return[];if(method==='run')return{success:true};return null;});const response=await updatePortalAdmin(ctx({db,path:'/api/portal-admin',method:'POST',role:'OWNER',userId:'owner_a',body:{action:'GRANT',userId:'external_a',projectId:'project_a',portalType:'FOUNDER',permissions:{viewFundraising:true}}}));assert.equal(response.status,200);const insert=db.calls.find(call=>/INSERT INTO activities/i.test(call.sql));assert.ok(insert);assert.equal(insert.bindings[3],'owner_a');const grant=JSON.parse(insert.bindings[6]);assert.equal(grant.userId,'external_a');assert.equal(grant.projectId,'project_a');});