import { test,expect } from '@playwright/test';

const home={user:{userId:'external_a',fullName:'Founder A',email:'founder@example.test'},tenant:{id:'tenant_a',slug:'tenant-a',name:'AKARI House'},projects:[{id:'project_a',name:'FounderCo',category:'Web3',region:'Europe',country:'Germany',website:'https://founder.example',lifecycleStatus:'CLIENT',portalType:'FOUNDER',permissions:{viewEngagement:true,viewCampaigns:true,viewFundraising:true,viewDocuments:true,viewReports:true,updateOwnTasks:true,answerDiligence:true}}],empty:false,security:{portalOnly:true,tenantScoped:true,explicitProjectGrants:true}};
const project={project:{id:'project_a',name:'FounderCo',category:'Web3',region:'Europe',country:'Germany',website:'https://founder.example',lifecycleStatus:'CLIENT'},grant:home.projects[0],tasks:[{id:'task_a',title:'Upload updated deck',description:'Founder action',status:'TODO',priority:'HIGH',dueAt:'2026-08-20',completedAt:null}],campaigns:[{id:'campaign_a',name:'Launch Campaign',status:'ACTIVE',startDate:'2026-08-01',endDate:'2026-08-31',region:'Global',trackingEnabled:true}],fundraising:{id:'room_a',roundName:'Seed',stage:'DILIGENCE',roundType:'SAFE',fundingStage:'SEED',currency:'USD',targetAmount:500000,committedAmount:100000,valuation:5000000,minimumTicket:25000,targetCloseDate:'2026-10-31',readinessScore:82,thesis:'Scale distribution.',nextAction:'Resolve diligence',dataRoomDocuments:[{id:'doc_a',title:'Pitch Deck',category:'PITCH',url:'https://docs.example/deck',version:'1.0',confidentiality:'RESTRICTED',status:'ACTIVE'}],diligenceRequests:[{id:'dd_a',investorName:'North Star Ventures',title:'Security architecture',category:'SECURITY',status:'IN_PROGRESS',dueDate:'2026-08-20',response:'',evidenceUrl:''}],investorQuestions:[{id:'q_a',investorName:'North Star Ventures',question:'What is the GTM moat?',answer:'',status:'OPEN',askedAt:'2026-08-10'}]},disclosures:{internalNotesExcluded:true,privateInvestorContactsExcluded:true,commercialNegotiationsExcluded:true,financeExcluded:true,creatorPaymentsExcluded:true}};

async function mockPortal(page,updates=[]){await page.route('**/api/portal**',async route=>{const req=route.request(),url=new URL(req.url());if(req.method()==='PATCH'){updates.push(JSON.parse(req.postData()||'{}'));return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({updated:true,item:project})});}const body=url.pathname==='/api/portal'?home:project;return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(body)});});}

test('external founder portal shows only granted project-safe collaboration data',async({page})=>{await mockPortal(page);await page.goto('/portal/index.html');await expect(page.getByRole('heading',{name:'FounderCo'})).toBeVisible();await expect(page.getByText('Upload updated deck')).toBeVisible();await page.getByRole('button',{name:'Campaigns'}).click();await expect(page.getByText('Launch Campaign')).toBeVisible();await page.getByRole('button',{name:'Capital Room'}).click();await expect(page.getByText('Seed',{exact:true})).toBeVisible();await expect(page.getByText('Pitch Deck')).toBeVisible();await expect(page.getByText('What is the GTM moat?')).toBeVisible();await expect(page.getByText(/internal notes, private investor contacts, commercial negotiations, finance records and Creator\/KOL payments are excluded/i)).toBeVisible();await expect(page.getByText(/billing@|contact@|private note/i)).toHaveCount(0);});

test('external portal task and diligence actions use only project-scoped portal PATCH',async({page})=>{const updates=[];await mockPortal(page,updates);await page.goto('/portal/index.html');const task=page.locator('[data-task="task_a"]');await task.selectOption('DONE');await expect.poll(()=>updates.some(item=>item.action==='UPDATE_TASK'&&item.taskId==='task_a'&&item.status==='DONE')).toBeTruthy();await page.getByRole('button',{name:'Capital Room'}).click();await page.locator('[data-question="q_a"] textarea').fill('Our distribution moat combines community and partner channels.');await page.locator('[data-question="q_a"] button').click();await expect.poll(()=>updates.some(item=>item.action==='ANSWER_INVESTOR_QUESTION'&&item.questionId==='q_a')).toBeTruthy();});

test('external portal is mobile-safe without horizontal page overflow',async({page})=>{await page.setViewportSize({width:390,height:844});await mockPortal(page);await page.goto('/portal/index.html');await expect(page.getByRole('heading',{name:'FounderCo'})).toBeVisible();const overflow=await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth);expect(overflow).toBeLessThanOrEqual(1);await expect(page.locator('.projects')).toBeVisible();});