import { test,expect } from '@playwright/test';

const legacy={items:[{id:'room_a',projectId:'project_a',projectName:'Founder A',roundName:'Seed',stage:'OUTREACH',currency:'USD',targetAmount:500000,committedAmount:100000,valuation:5000000,roundType:'SAFE',ownerUserId:'user_owner',targetCloseDate:'2026-10-31',thesis:'Raise seed capital to scale distribution.',nextAction:'Advance priority investors',readinessScore:74,dataRoomDocuments:[{id:'doc_a',title:'Pitch deck',category:'PITCH',url:'https://docs.example/deck',version:'1.0'}],investorAccess:[],diligenceRequests:[{id:'dd_a',title:'Security architecture',status:'IN_PROGRESS',dueDate:'2026-09-01'}],investorQuestions:[{id:'q_a',investorPipelineId:'legacy_target',question:'What is the GTM moat?',status:'OPEN',answer:''}],investorPipeline:[{id:'legacy_target',investorName:'North Star Ventures',stage:'DILIGENCE',decisionMaker:'Alex Partner',nextAction:'Answer diligence questions'}],diligenceSummary:{documents:1,activeAccess:0,openRequests:1,openQuestions:1}}],projects:[],investorProjects:[],summary:{active:1,total:1,target:500000,committed:100000,remaining:400000,investors:1,averageReadiness:74},permissions:{canWrite:true,canFinance:true}};
const intelligence={storageMode:'NORMALIZED_D1',migrationRequired:false,readOnly:false,rounds:[{id:'round_a',project_id:'project_a',project_name:'Founder A',round_name:'Seed',stage:'OUTREACH',currency:'USD',target_amount:500000,valuation:5000000,instrument:'SAFE',owner_user_id:'user_owner',target_close_date:'2026-10-31',thesis:'Raise seed capital to scale distribution.',next_action:'Advance priority investors',readiness_score:74,economics:{weightedPipeline:280000,confirmedCommitments:100000,fundsReceived:50000}}],summary:{rounds:1,activeRounds:1,targets:1,investorOrganisations:1,evidenceSources:3,targetAmount:500000,weightedPipeline:280000,confirmedCommitments:100000,fundsReceived:50000},permissions:{canWrite:true,canFinance:true}};
const universe={storageMode:'NORMALIZED_D1',migrationRequired:false,readOnly:false,organisations:[{id:'org_a',name:'North Star Ventures'}],people:[{id:'person_a',organisation_id:'org_a',full_name:'Alex Partner'}],sources:[],claims:[],portfolio:[],targets:[],reviewQueue:[],duplicates:[],summary:{organisations:1,people:1,decisionMakers:1,claims:0,verifiedClaims:0},permissions:{canWrite:true,canReview:true}};
const targeting={storageMode:'NORMALIZED_D1',migrationRequired:false,readOnly:false,rounds:[{id:'round_a',project_id:'project_a',project_name:'Founder A',round_name:'Seed',stage:'OUTREACH',currency:'USD',target_amount:500000,expectedChecks:{researched:300000,softCircle:0,committed:0},stageSummary:[{stage:'READY',count:1,expectedCheck:300000,weightedExpected:150000}],targets:[{id:'target_a',round_id:'round_a',organisation_id:'org_a',organisation_name:'North Star Ventures',stage:'READY',fit_score:87,primary_person_id:'person_a',primary_person_name:'Alex Partner',expected_check:300000,probability_percentage:50,next_follow_up_at:'2026-09-01T10:00:00.000Z',next_action:'Send founder-approved introduction',introduction_paths:[{id:'intro_a',verification_status:'VERIFIED',consent_status:'GRANTED',request_status:'PLANNED'}]}]}],focusedLists:{overdueFollowUps:[],followUpsThisWeek:[],readyForIntroduction:[],consentRequired:[],researchNeeded:[],highFitNoAction:[],softCircle:[]},summary:{rounds:1,targets:1,warmPaths:1,verifiedPaths:1,consentGranted:1,overdueFollowUps:0,expectedPipeline:300000,softCircle:0},permissions:{canWrite:true,canApprove:true}};
const outreach={storageMode:'NORMALIZED_D1',targets:targeting.rounds[0].targets,drafts:[{id:'draft_a',projectId:'project_a',roundId:'round_a',targetId:'target_a',investorName:'North Star Ventures',status:'DRAFT',approvalState:{founder:true,akari:false,fullyApproved:false}}],meetings:[],members:[],summary:{drafts:1,awaitingFounder:0,awaitingAkari:1,approved:0,sent:0,upcomingMeetings:0,followUpsDue:0},permissions:{canWrite:true,canApprove:true},safety:{directSend:false,approvalRequired:true,exactContentApproval:true}};
const closing={storageMode:'NORMALIZED_D1',migrationRequired:false,readOnly:false,items:[{id:'round_a',projectId:'project_a',projectName:'Founder A',roundName:'Seed',stage:'OUTREACH',currency:'USD',instrument:'SAFE',sourceModel:'NORMALIZED',summary:{target:500000,confirmed:100000,allocated:100000,received:50000,outstanding:50000,coverageRatio:20,canClose:false,blockers:['Active allocation remains outstanding'],fundedCount:0,commitmentCount:1},commitments:[],receipts:[],updates:[]}],permissions:{canWrite:true,canApprove:true,canFinance:true},controls:{},ai:{required:false}};
const strategy={storageMode:'NORMALIZED_D1',migrationRequired:false,rounds:[{id:'round_a',projectId:'project_a',projectName:'Founder A',roundName:'Seed',stage:'OUTREACH',instrument:'SAFE',currency:'USD',targetAmount:500000,termSheets:[{id:'term_a',status:'REVIEWING',investorName:'North Star Ventures',instrument:'SAFE',proposedInvestment:250000,riskFlags:[],riskCount:0}],capTableScenarios:[],strategicFunding:[]}],members:[],summary:{termSheets:1,termSheetsInReview:1,approvedTermSheets:0,capTableScenarios:0,strategicFunding:0},permissions:{canWrite:true,canApprove:true,canFinance:true},controls:{},disclaimers:{legal:'Not legal advice'}};

const commandPayloads={
  '/api/fundraising':legacy,
  '/api/fundraising/intelligence':intelligence,
  '/api/fundraising/universe':universe,
  '/api/fundraising/targeting':targeting,
  '/api/fundraising/outreach':outreach,
  '/api/fundraising/closing':closing,
  '/api/fundraising/strategy':strategy,
};
function generic(url){const parsed=new URL(url),path=`${parsed.pathname}${parsed.search}`;if(commandPayloads[path])return commandPayloads[path];if(path==='/api/me')return{user:{userId:'user_owner',tenantId:'tenant_akari_house',tenantSlug:'akari-house',email:'owner@example.com',fullName:'Muaz Test',role:'OWNER',financeAccess:true}};if(path==='/api/profile')return{user:{id:'user_owner',fullName:'Muaz Test',email:'owner@example.com',status:'ACTIVE'}};if(path==='/api/team')return{items:[{userId:'user_owner',fullName:'Muaz Test',role:'OWNER',status:'ACTIVE',financeAccess:true}],total:1};if(path==='/api/billing-profile')return{tenant:{name:'AKARI House',baseCurrency:'USD'},billingProfile:{legalName:'AKARI House',invoicePrefix:'AKARI',defaultTaxRate:0,defaultPaymentTermsDays:14}};if(path==='/api/dashboard')return{currency:'USD',metrics:{monthlyTarget:0,revenueBooked:0,revenueCollected:0,netRevenue:0,weightedPipeline:0,activeOpportunities:0,yearToDateRevenue:0,activeCustomers:0,activeCampaigns:0,activePartners:0,outstandingPayments:0,referralRewardsDue:0}};if(path==='/api/ai/providers')return{enabled:false,primaryProvider:'OPENAI',fallbackProvider:'ANTHROPIC',allowFallback:false,models:{},enabledPurposes:[],maxOutputTokens:1200,canManage:true,providers:[],purposes:[],secretRule:'Optional'};if(path==='/api/production-readiness')return{tenant:{name:'AKARI House',plan_code:'FOUNDING',timezone:'Europe/Berlin'},generatedAt:'2026-08-11T00:00:00.000Z',counts:{},roles:[],automaticChecks:[],manualChecks:[],readinessScore:0,canManage:true,canExport:true};if(path==='/api/tasks?scope=mine'||path==='/api/tasks?scope=mine&includeCompleted=1')return{items:[],total:0};if(path==='/api/projects?limit=5')return{items:[],total:0};if(['/api/opportunities','/api/campaigns','/api/payments','/api/invoices','/api/partners','/api/contacts'].includes(path))return{items:[],total:0};if(path==='/api/reports')return{pipelineByStage:[],revenueByMonth:[]};if(parsed.pathname.startsWith('/api/akari-leads'))return{items:[],total:0,categories:[],owners:[],canWrite:true};return{items:[],total:0};}
async function boot(page,{requests=[]}={}){await page.route('**/api/**',async route=>{const req=route.request();requests.push({path:new URL(req.url()).pathname,method:req.method()});await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(generic(req.url()))});});await page.goto('/app/akari-house/fundraising');await expect(page.getByRole('heading',{name:'Fundraising',exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:'Founder Capital Command Centre',exact:true})).toBeVisible();}

test('Founder Capital Room unifies canonical fundraising evidence into deterministic readiness and one next action',async({page})=>{const requests=[];await boot(page,{requests});const command=page.locator('#founder-capital-command-r67');await expect(command.getByText('90/100',{exact:false})).toBeVisible();await expect(command.getByText('74%',{exact:true})).toBeVisible();await expect(command.getByText('Resolve outstanding investor diligence',{exact:true})).toBeVisible();await expect(command.getByText('$500,000',{exact:true}).first()).toBeVisible();await expect(command.getByText('$280,000',{exact:true})).toBeVisible();await expect(command.getByText('1/1 controls satisfied',{exact:false})).toHaveCount(0);await expect(command.getByText('13/15 controls satisfied',{exact:false})).toBeVisible();await expect(command.getByText('Investor questions answered')).toBeVisible();await expect(command.getByText('Approved/sent outreach evidence exists')).toBeVisible();const fundraisingWrites=requests.filter(item=>item.path.startsWith('/api/fundraising')&&item.method!=='GET');expect(fundraisingWrites).toEqual([]);});

test('Capital Room navigation hands off to existing Data Room, Targeting, Terms and Closing modules',async({page})=>{await boot(page);await expect(page.locator('#fundraising-targeting-root')).toBeVisible();await expect(page.locator('#fundraising-strategy-root')).toBeVisible();await expect(page.locator('#fundraising-closing-centre')).toBeVisible();await page.locator('[data-fcr67-nav="terms"]').first().click();await expect(page.locator('#fundraising-strategy-root')).toHaveClass(/fcr67-focus/);await page.locator('[data-fcr67-nav="investors"]').first().click();await expect(page.locator('#fundraising-targeting-root')).toHaveClass(/fcr67-focus/);await page.locator('[data-fcr67-nav="data-room"]').first().click();await expect(page.getByRole('dialog',{name:'Fundraising data room'})).toBeVisible();});

test('Founder Capital Room command centre remains page-safe on mobile',async({page})=>{await page.setViewportSize({width:390,height:844});await boot(page);const overflow=await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth);expect(overflow).toBeLessThanOrEqual(1);await expect(page.locator('#founder-capital-command-r67')).toBeVisible();await expect(page.locator('.fcr67-nav')).toBeVisible();});