import { test,expect } from '@playwright/test';

const baseRound={id:'round_a',projectId:'project_a',projectName:'Founder A',roundName:'Seed',stage:'CLOSING',instrument:'SAFE',currency:'USD',targetAmount:500000,valuation:5000000,targetCloseDate:'2026-08-31T00:00:00.000Z',sourceModel:'NORMALIZED'};
const signedCommitment={id:'commit_a',roundId:'round_a',targetId:'target_a',investorName:'North Star Ventures',personName:'Alex Partner',status:'SIGNED',committedAmount:250000,allocatedAmount:200000,receivedAmount:100000,currency:'USD',instrument:'SAFE',signedDocumentUrl:'https://docs.example/safe',signedAt:'2026-08-02T10:00:00.000Z'};
const fundedCommitment={...signedCommitment,status:'FUNDED',receivedAmount:200000};
const blockedPayload={storageMode:'NORMALIZED_D1',migrationRequired:false,readOnly:false,members:[{id:'user_owner',full_name:'Muaz',role:'OWNER'}],items:[{...baseRound,commitments:[signedCommitment],receipts:[{id:'receipt_a',roundId:'round_a',commitmentId:'commit_a',investorName:'North Star Ventures',amount:100000,cumulativeReceived:100000,currency:'USD',rail:'BANK_WIRE',reference:'wire-1',receivedAt:'2026-08-03T10:00:00.000Z',status:'RECORDED'}],updates:[],summary:{target:500000,soft:0,confirmed:250000,allocated:200000,received:100000,outstanding:100000,remaining:400000,coverageRatio:20,commitmentCount:1,fundedCount:0,blockers:['Every active commitment must be funded or cancelled','All allocated capital must be reconciled as received'],canClose:false}}],permissions:{canWrite:true,canApprove:true,canFinance:true},controls:{commitmentStatuses:['SOFT','CONFIRMED','SIGNED','FUNDED','CANCELLED'],updateStatuses:['DRAFT','APPROVED','PUBLISHED','ARCHIVED'],paymentRails:['BANK_WIRE','USDT','USDC','OTHER']},ai:{required:false,enabled:false}};
const readyPayload={...blockedPayload,items:[{...baseRound,commitments:[fundedCommitment],receipts:[{id:'receipt_a',roundId:'round_a',commitmentId:'commit_a',investorName:'North Star Ventures',amount:200000,cumulativeReceived:200000,currency:'USD',rail:'BANK_WIRE',reference:'wire-1',receivedAt:'2026-08-03T10:00:00.000Z',status:'RECORDED'}],updates:[{id:'update_a',roundId:'round_a',projectId:'project_a',title:'August investor update',period:'August 2026',status:'DRAFT',summary:'Product and hiring progress.'}],summary:{target:500000,soft:0,confirmed:250000,allocated:200000,received:200000,outstanding:0,remaining:300000,coverageRatio:40,commitmentCount:1,fundedCount:1,blockers:[],canClose:true}}]};
const targetingPayload={storageMode:'NORMALIZED_D1',migrationRequired:false,readOnly:false,rounds:[{id:'round_a',targets:[{id:'target_a',organisation_name:'North Star Ventures',primary_person_name:'Alex Partner',stage:'COMMITTED'},{id:'target_b',organisation_name:'Beacon Fund',primary_person_name:'Dana Principal',stage:'SOFT_CIRCLE'}]}],people:[],connectors:[],members:[],sources:[],focusedLists:{},summary:{},permissions:{canWrite:true,canApprove:true}};
const universePayload={storageMode:'NORMALIZED_D1',migrationRequired:false,readOnly:false,organisations:[],people:[],sources:[],claims:[],portfolio:[],targets:[],reviewQueue:[],duplicates:[],summary:{},permissions:{canWrite:true,canReview:true}};
function generic(url){const parsed=new URL(url),path=`${parsed.pathname}${parsed.search}`;if(path==='/api/me')return{user:{userId:'user_owner',tenantId:'tenant_akari_house',tenantSlug:'akari-house',email:'owner@example.com',fullName:'Muaz Test',role:'OWNER',financeAccess:true}};if(path==='/api/profile')return{user:{id:'user_owner',fullName:'Muaz Test',email:'owner@example.com',status:'ACTIVE'}};if(path==='/api/team')return{items:[{userId:'user_owner',fullName:'Muaz Test',role:'OWNER',status:'ACTIVE',financeAccess:true}],total:1};if(path==='/api/billing-profile')return{tenant:{name:'AKARI House',baseCurrency:'USD'},billingProfile:{legalName:'AKARI House',invoicePrefix:'AKARI',defaultTaxRate:0,defaultPaymentTermsDays:14}};if(path==='/api/dashboard')return{currency:'USD',metrics:{monthlyTarget:0,revenueBooked:0,revenueCollected:0,netRevenue:0,weightedPipeline:0,activeOpportunities:0,yearToDateRevenue:0,activeCustomers:0,activeCampaigns:0,activePartners:0,outstandingPayments:0,referralRewardsDue:0}};if(path==='/api/fundraising')return{items:[],projects:[],investorProjects:[],summary:{active:0,total:0,target:0,committed:0,remaining:0,investors:0,averageReadiness:0},permissions:{canWrite:true,canFinance:true}};if(path==='/api/fundraising/universe')return universePayload;if(path==='/api/fundraising/targeting')return targetingPayload;if(path==='/api/fundraising/outreach')return{storageMode:'NORMALIZED_D1',targets:[],drafts:[],meetings:[],members:[],summary:{},permissions:{canWrite:true,canApprove:true},controls:{},safety:{directSend:false}};if(path==='/api/ai/providers')return{enabled:false,primaryProvider:'OPENAI',fallbackProvider:'ANTHROPIC',allowFallback:false,models:{},enabledPurposes:[],maxOutputTokens:1200,canManage:true,providers:[],purposes:[],secretRule:'Optional'};if(path==='/api/production-readiness')return{tenant:{name:'AKARI House',plan_code:'FOUNDING',timezone:'Europe/Berlin'},generatedAt:'2026-08-03T11:00:00.000Z',counts:{},roles:[],automaticChecks:[],manualChecks:[],readinessScore:0,canManage:true,canExport:true};if(path==='/api/tasks?scope=mine'||path==='/api/tasks?scope=mine&includeCompleted=1')return{items:[],total:0};if(path==='/api/projects?limit=5')return{items:[],total:0};if(['/api/opportunities','/api/campaigns','/api/payments','/api/invoices','/api/partners','/api/contacts'].includes(path))return{items:[],total:0};if(path==='/api/reports')return{pipelineByStage:[],revenueByMonth:[]};if(parsed.pathname.startsWith('/api/akari-leads'))return{items:[],total:0,categories:[],owners:[],canWrite:true};return{items:[],total:0};}
async function boot(page,{payload=blockedPayload,captures=[]}={}){await page.route('**/api/**',async route=>{const request=route.request(),parsed=new URL(request.url());if(parsed.pathname==='/api/fundraising/closing'){if(request.method()==='POST')captures.push(request.postDataJSON());await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(request.method()==='GET'?payload:{item:{id:'saved'}})});return;}await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(generic(request.url()))});});await page.goto('/app/akari-house/dashboard');await expect(page.getByRole('heading',{name:/Good (morning|afternoon|evening), Muaz/i})).toBeVisible();}
async function openFundraising(page){await page.locator('[data-route="fundraising"]').first().click();await expect(page.getByRole('heading',{name:'Fundraising'})).toBeVisible();await expect(page.getByRole('heading',{name:'Commitments, Closing & Investor Relations'})).toBeVisible();}

test('manual-first closing workspace remains operational without an AI provider',async({page})=>{await boot(page);await openFundraising(page);await expect(page.getByText('AI is optional and currently not required.')).toBeVisible();await expect(page.getByText('$100,000').first()).toBeVisible();await expect(page.getByText('2 closing blockers')).toBeVisible();await page.locator('[data-fc-action="open"]').click();await expect(page.getByRole('dialog',{name:'Fundraising closing workspace'})).toBeVisible();await expect(page.getByText('Record funds')).toBeVisible();await expect(page.locator('[data-fc-action="close-round"]')).toBeDisabled();});

test('commitment form records investor target allocation and instrument manually',async({page})=>{const captures=[];await boot(page,{captures});await openFundraising(page);await page.locator('[data-fc-action="open"]').click();await page.locator('[data-fc-action="new-commitment"]').click();await expect(page.getByRole('dialog',{name:'Commitment form'})).toBeVisible();await page.locator('#fundraising-closing-modal select[name="targetId"]').selectOption('target_b');await page.locator('#fundraising-closing-modal input[name="committedAmount"]').fill('300000');await page.locator('#fundraising-closing-modal input[name="allocatedAmount"]').fill('250000');await page.locator('#fundraising-closing-modal input[name="instrument"]').fill('SAFE');await page.locator('#fundraising-closing-modal button[type="submit"]').click();await expect.poll(()=>captures.length).toBe(1);expect(captures[0]).toMatchObject({action:'save-commitment',roundId:'round_a',targetId:'target_b',status:'SOFT',committedAmount:300000,allocatedAmount:250000,instrument:'SAFE'});});

test('funds ledger records a cumulative manual receipt with transaction reference',async({page})=>{const captures=[];await boot(page,{captures});await openFundraising(page);await page.locator('[data-fc-action="open"]').click();await page.locator('[data-fc-action="record-funds"]').click();await expect(page.getByRole('dialog',{name:'Funds receipt form'})).toBeVisible();await page.locator('#fundraising-closing-modal input[name="amount"]').fill('100000');await page.locator('#fundraising-closing-modal select[name="rail"]').selectOption('USDT');await page.locator('#fundraising-closing-modal input[name="reference"]').fill('0xreceipt');await page.locator('#fundraising-closing-modal button[type="submit"]').click();await expect.poll(()=>captures.length).toBe(1);expect(captures[0]).toMatchObject({action:'record-funds',roundId:'round_a',id:'commit_a',amount:100000,rail:'USDT',reference:'0xreceipt'});});

test('governed closing captures below-target explanation and final notes',async({page})=>{const captures=[];await boot(page,{payload:readyPayload,captures});await openFundraising(page);await page.locator('[data-fc-action="open"]').click();await page.locator('[data-fc-action="close-round"]').click();await expect(page.getByRole('dialog',{name:'Close fundraising round'})).toBeVisible();await page.locator('#fundraising-closing-modal textarea[name="closingNotes"]').fill('Final documents signed and funds reconciled.');await page.locator('#fundraising-closing-modal textarea[name="shortfallReason"]').fill('Founder accepted a smaller strategic round.');await page.locator('#fundraising-closing-modal button[type="submit"]').click();await expect.poll(()=>captures.length).toBe(1);expect(captures[0]).toMatchObject({action:'close-round',roundId:'round_a',closingNotes:'Final documents signed and funds reconciled.',shortfallReason:'Founder accepted a smaller strategic round.'});});

test('post-raise investor update can be edited and Owner-published without AI',async({page})=>{const captures=[];await boot(page,{payload:readyPayload,captures});await openFundraising(page);await page.locator('[data-fc-action="open"]').click();await page.locator('[data-fc-action="tab"][data-tab="updates"]').click();await page.locator('[data-fc-action="edit-update"]').click();await expect(page.getByRole('dialog',{name:'Investor update form'})).toBeVisible();await page.locator('#fundraising-closing-modal textarea[name="summary"]').fill('Updated product, treasury and hiring progress.');await page.locator('#fundraising-closing-modal button[type="submit"]').click();await expect.poll(()=>captures.length).toBe(1);expect(captures[0]).toMatchObject({action:'save-investor-update',roundId:'round_a',id:'update_a',status:'DRAFT'});});

test('commitments closing and investor relations avoid mobile page overflow',async({page})=>{await page.setViewportSize({width:390,height:844});await boot(page);await page.locator('.mobile-bottom [data-action="open-sidebar"]').click();await page.locator('#sidebar [data-route="fundraising"]').click();await expect(page.getByRole('heading',{name:'Commitments, Closing & Investor Relations'})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)).toBeLessThanOrEqual(1);await page.locator('[data-fc-action="open"]').click();await expect(page.getByRole('dialog',{name:'Fundraising closing workspace'})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)).toBeLessThanOrEqual(1);});
