import { json,error,readJson } from '../../lib/response.js';
import { all,first,run,makeId,nowIso } from '../../lib/db.js';
import { requireTenant,requireRole } from '../../lib/permissions.js';
import { parseFundraisingFlags } from '../../lib/fundraising-os.js';
import { DATA_ROOM_CATEGORIES,defaultRequirements,legacyRoomForRound,legacyDocuments,legacyAccess,legacyDiligence,sanitizeRequirement,sanitizeDocument,sanitizeAccess,sanitizeDiligence,effectiveAccessStatus,jsonList } from '../../lib/data-room-r72.js';

const WRITE_ROLES=['OWNER','ADMIN','BD_MANAGER'];
const MISSING_SCHEMA=/(no such table.*fundraising_data_room|D1_ERROR.*fundraising_data_room|SQLITE_ERROR.*fundraising_data_room)/i;
const text=(value,max=8000)=>String(value??'').trim().slice(0,max);

async function ensureSchema(db){try{await first(db,'SELECT id FROM fundraising_data_room_documents LIMIT 1');}catch(cause){if(MISSING_SCHEMA.test(String(cause?.message||''))){const e=new Error('Data Room migration 0005 must be applied before R72 is available');e.status=503;throw e;}throw cause;}}
async function tenantRound(db,tenantId,roundId){return first(db,`SELECT r.*,p.name AS project_name,p.country AS project_country,p.region AS project_region FROM fundraising_rounds r JOIN projects p ON p.id=r.project_id AND p.tenant_id=r.tenant_id WHERE r.tenant_id=? AND r.id=? LIMIT 1`,[tenantId,roundId]);}
async function tenantRounds(db,tenantId){return all(db,`SELECT r.*,p.name AS project_name FROM fundraising_rounds r JOIN projects p ON p.id=r.project_id AND p.tenant_id=r.tenant_id WHERE r.tenant_id=? ORDER BY CASE WHEN r.stage IN ('CLOSED','PAUSED') THEN 1 ELSE 0 END,r.updated_at DESC`,[tenantId]);}
async function member(db,tenantId,userId){if(!userId)return null;return first(db,`SELECT u.id FROM users u JOIN tenant_memberships tm ON tm.user_id=u.id WHERE tm.tenant_id=? AND tm.status='ACTIVE' AND u.status='ACTIVE' AND u.id=? LIMIT 1`,[tenantId,userId]);}
async function settingFlags(db,tenantId){const row=await first(db,'SELECT feature_flags_json FROM tenant_settings WHERE tenant_id=? LIMIT 1',[tenantId]);return parseFundraisingFlags(row?.feature_flags_json).flags;}

async function audit(db,auth,action,entityType,entityId,before,after){await run(db,`INSERT INTO audit_logs(id,tenant_id,user_id,action,entity_type,entity_id,before_data,after_data,created_at) VALUES(?,?,?,?,?,?,?,?,?)`,[makeId('aud'),auth.tenantId,auth.userId,action,entityType,entityId,JSON.stringify(before||{}),JSON.stringify(after||{}),nowIso()]);}
async function activity(db,auth,round,eventType,meta={}){await run(db,`INSERT INTO fundraising_data_room_activity(id,tenant_id,project_id,round_id,access_id,investor_pipeline_id,document_id,version_id,actor_user_id,event_type,occurred_at,metadata_json) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)`,[makeId('dra'),auth.tenantId,round.project_id,round.id,meta.accessId||null,meta.investorPipelineId||null,meta.documentId||null,meta.versionId||null,auth.userId||null,eventType,nowIso(),JSON.stringify(meta.metadata||{})]);}

async function requirements(db,tenantId,roundId){return all(db,'SELECT * FROM fundraising_data_room_requirements WHERE tenant_id=? AND round_id=? ORDER BY category,title',[tenantId,roundId]);}
async function documents(db,tenantId,roundId){const docs=await all(db,'SELECT * FROM fundraising_data_room_documents WHERE tenant_id=? AND round_id=? ORDER BY category,title',[tenantId,roundId]);if(!docs.length)return[];const ids=docs.map(x=>x.id),marks=ids.map(()=>'?').join(',');const versions=await all(db,`SELECT * FROM fundraising_data_room_document_versions WHERE tenant_id=? AND document_id IN (${marks}) ORDER BY document_id,version_number DESC`,[tenantId,...ids]);return docs.map(doc=>({...doc,versions:versions.filter(v=>v.document_id===doc.id),currentVersion:versions.find(v=>v.document_id===doc.id&&Number(v.version_number)===Number(doc.current_version_number))||versions.find(v=>v.document_id===doc.id)||null}));}
async function accessRows(db,tenantId,roundId){const rows=await all(db,'SELECT * FROM fundraising_data_room_access WHERE tenant_id=? AND round_id=? ORDER BY updated_at DESC',[tenantId,roundId]);return rows.map(row=>({...row,effective_status:effectiveAccessStatus(row),allowed_categories:jsonList(row.allowed_categories_json)}));}
async function diligenceRows(db,tenantId,roundId){const rows=await all(db,'SELECT * FROM fundraising_diligence_requests WHERE tenant_id=? AND round_id=? ORDER BY CASE status WHEN \'OPEN\' THEN 0 WHEN \'IN_PROGRESS\' THEN 1 WHEN \'WAITING_FOUNDER\' THEN 2 ELSE 3 END,due_date,updated_at DESC',[tenantId,roundId]);if(!rows.length)return[];const ids=rows.map(x=>x.id),marks=ids.map(()=>'?').join(',');const links=await all(db,`SELECT request_id,document_id FROM fundraising_diligence_request_documents WHERE tenant_id=? AND request_id IN (${marks})`,[tenantId,...ids]);return rows.map(row=>({...row,document_ids:links.filter(x=>x.request_id===row.id).map(x=>x.document_id)}));}
async function targetRows(db,tenantId,roundId){return all(db,`SELECT t.id,t.stage,t.organisation_id,o.name AS investor_name,p.full_name AS primary_person FROM fundraising_targets t JOIN investor_organisations o ON o.id=t.organisation_id AND o.tenant_id=t.tenant_id LEFT JOIN investor_people p ON p.id=t.primary_person_id AND p.tenant_id=t.tenant_id WHERE t.tenant_id=? AND t.round_id=? ORDER BY t.priority DESC,o.name COLLATE NOCASE`,[tenantId,roundId]);}
async function recentActivity(db,tenantId,roundId){return all(db,'SELECT * FROM fundraising_data_room_activity WHERE tenant_id=? AND round_id=? ORDER BY occurred_at DESC LIMIT 100',[tenantId,roundId]);}

async function workspace(db,tenantId,round){const [reqs,docs,access,diligence,targets,events]=await Promise.all([requirements(db,tenantId,round.id),documents(db,tenantId,round.id),accessRows(db,tenantId,round.id),diligenceRows(db,tenantId,round.id),targetRows(db,tenantId,round.id),recentActivity(db,tenantId,round.id)]);const missing=reqs.filter(x=>x.required&&['MISSING','REQUESTED'].includes(x.status)).length;return{round:{id:round.id,projectId:round.project_id,projectName:round.project_name,roundName:round.round_name,stage:round.stage,legacyRoomId:round.legacy_room_id||null},categories:DATA_ROOM_CATEGORIES,requirements:reqs,documents:docs,access,diligence,targets,activity:events,summary:{documents:docs.filter(x=>x.status==='ACTIVE').length,versions:docs.reduce((n,x)=>n+x.versions.length,0),missingRequirements:missing,activeAccess:access.filter(x=>x.effective_status==='GRANTED').length,ndaPending:access.filter(x=>['REQUESTED','PENDING'].includes(x.nda_status)).length,openDiligence:diligence.filter(x=>!['RESOLVED','CLOSED'].includes(x.status)).length}};}

async function bootstrap(db,auth,round){const tenantId=auth.tenantId;let created=0,imported=0;const existingReqs=await requirements(db,tenantId,round.id);if(!existingReqs.length){let web3Relevant=true;try{const token=await first(db,"SELECT data_json,status FROM founder_onboarding_items WHERE tenant_id=? AND round_id=? AND item_key='TOKENOMICS' LIMIT 1",[tenantId,round.id]);if(token){const d=JSON.parse(token.data_json||'{}');web3Relevant=d.web3Relevant!==false;}}catch{}for(const req of defaultRequirements({web3Relevant})){await run(db,`INSERT OR IGNORE INTO fundraising_data_room_requirements(id,tenant_id,project_id,round_id,category,requirement_key,title,required,status,notes,created_at,updated_at,created_by,updated_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,[makeId('drr'),tenantId,round.project_id,round.id,req.category,req.requirementKey,req.title,req.required?1:0,req.status,req.notes||null,nowIso(),nowIso(),auth.userId,auth.userId]);created++;}}
  const flags=await settingFlags(db,tenantId),legacy=legacyRoomForRound(flags,round);if(legacy){
    for(const raw of legacyDocuments(legacy)){if(await first(db,'SELECT id FROM fundraising_data_room_documents WHERE tenant_id=? AND round_id=? AND legacy_document_id=? LIMIT 1',[tenantId,round.id,raw.id]))continue;const item=sanitizeDocument(raw);if(!item.title||!item.secureUrl)continue;const id=makeId('drd'),vid=makeId('drv'),now=nowIso();await run(db,`INSERT INTO fundraising_data_room_documents(id,tenant_id,project_id,round_id,legacy_document_id,requirement_id,category,title,confidentiality,status,current_version_number,notes,created_at,updated_at,created_by,updated_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,[id,tenantId,round.project_id,round.id,raw.id||null,null,item.category,item.title,item.confidentiality,item.status,1,item.notes||null,now,now,auth.userId,auth.userId]);await run(db,`INSERT INTO fundraising_data_room_document_versions(id,tenant_id,document_id,version_number,version_label,secure_url,change_note,uploaded_by_source,created_at,created_by) VALUES(?,?,?,?,?,?,?,?,?,?)`,[vid,tenantId,id,1,item.versionLabel||'1.0',item.secureUrl,'Imported from R5 Capital Room','IMPORT',now,auth.userId]);await activity(db,auth,round,'DOCUMENT_UPLOADED',{documentId:id,versionId:vid,metadata:{source:'R5_LEGACY_IMPORT'}});imported++;}
    for(const raw of legacyAccess(legacy)){if(!raw.investorPipelineId||await first(db,'SELECT id FROM fundraising_data_room_access WHERE tenant_id=? AND round_id=? AND investor_pipeline_id=? LIMIT 1',[tenantId,round.id,raw.investorPipelineId]))continue;const item=sanitizeAccess(raw),now=nowIso(),id=makeId('dra');await run(db,`INSERT INTO fundraising_data_room_access(id,tenant_id,project_id,round_id,legacy_access_id,investor_pipeline_id,nda_status,access_status,allowed_categories_json,granted_at,expires_at,notes,created_at,updated_at,created_by,updated_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,[id,tenantId,round.project_id,round.id,raw.id||null,item.investorPipelineId,item.ndaStatus,item.accessStatus,JSON.stringify(item.allowedCategories),raw.grantedAt||null,item.expiresAt||null,item.notes||null,now,now,auth.userId,auth.userId]);imported++;}
    for(const raw of legacyDiligence(legacy)){if(await first(db,'SELECT id FROM fundraising_diligence_requests WHERE tenant_id=? AND round_id=? AND legacy_request_id=? LIMIT 1',[tenantId,round.id,raw.id]))continue;const item=sanitizeDiligence(raw);if(!item.title)continue;const now=nowIso(),id=makeId('dd');await run(db,`INSERT INTO fundraising_diligence_requests(id,tenant_id,project_id,round_id,legacy_request_id,investor_pipeline_id,title,category,status,owner_user_id,due_date,founder_response,internal_notes,resolved_at,created_at,updated_at,created_by,updated_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,[id,tenantId,round.project_id,round.id,raw.id||null,item.investorPipelineId||null,item.title,item.category,item.status,item.ownerUserId||null,item.dueDate||null,item.founderResponse||null,item.internalNotes||null,['RESOLVED','CLOSED'].includes(item.status)?now:null,now,now,auth.userId,auth.userId]);imported++;}
  }
  return{createdRequirements:created,importedLegacyRecords:imported};
}

export async function onRequestGet(context){try{const auth=context.data.auth,tenantId=requireTenant(auth);if(!context.env.DB)return error('D1 binding DB is not configured',500);await ensureSchema(context.env.DB);const url=new URL(context.request.url),roundId=text(url.searchParams.get('roundId'),120);if(!roundId){const rounds=await tenantRounds(context.env.DB,tenantId);return json({items:rounds.map(r=>({id:r.id,projectId:r.project_id,projectName:r.project_name,roundName:r.round_name,stage:r.stage})),permissions:{canWrite:WRITE_ROLES.includes(auth.role)}});}const round=await tenantRound(context.env.DB,tenantId,roundId);if(!round)return error('Fundraising round was not found in this workspace',404);return json({...await workspace(context.env.DB,tenantId,round),permissions:{canWrite:WRITE_ROLES.includes(auth.role)}});}catch(cause){console.error('R72 data room read failed',cause);return error(cause.message||'Data Room could not be loaded',Number(cause.status||500));}}

export async function onRequestPost(context){try{const auth=context.data.auth,tenantId=requireTenant(auth);requireRole(auth,WRITE_ROLES);if(!context.env.DB)return error('D1 binding DB is not configured',500);await ensureSchema(context.env.DB);const body=await readJson(context.request),action=text(body.action,80).toLowerCase(),round=await tenantRound(context.env.DB,tenantId,text(body.roundId,120));if(!round)return error('Fundraising round was not found in this workspace',404);
  if(action==='bootstrap'){const result=await bootstrap(context.env.DB,auth,round);await audit(context.env.DB,auth,'DATA_ROOM_R72_BOOTSTRAPPED','FUNDRAISING_ROUND',round.id,{},result);return json({updated:true,...result,workspace:await workspace(context.env.DB,tenantId,round)});}
  if(action==='save-requirement'){const existing=body.item?.id?await first(context.env.DB,'SELECT * FROM fundraising_data_room_requirements WHERE tenant_id=? AND round_id=? AND id=? LIMIT 1',[tenantId,round.id,body.item.id]):null;const item=sanitizeRequirement(body.item||{},existing||{});if(!item.requirementKey||!item.title)return error('Requirement key and title are required',422);const id=existing?.id||makeId('drr'),now=nowIso();if(existing)await run(context.env.DB,'UPDATE fundraising_data_room_requirements SET category=?,requirement_key=?,title=?,required=?,status=?,notes=?,updated_at=?,updated_by=? WHERE tenant_id=? AND round_id=? AND id=?',[item.category,item.requirementKey,item.title,item.required?1:0,item.status,item.notes||null,now,auth.userId,tenantId,round.id,id]);else await run(context.env.DB,'INSERT INTO fundraising_data_room_requirements(id,tenant_id,project_id,round_id,category,requirement_key,title,required,status,notes,created_at,updated_at,created_by,updated_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)',[id,tenantId,round.project_id,round.id,item.category,item.requirementKey,item.title,item.required?1:0,item.status,item.notes||null,now,now,auth.userId,auth.userId]);await audit(context.env.DB,auth,existing?'DATA_ROOM_REQUIREMENT_UPDATED':'DATA_ROOM_REQUIREMENT_CREATED','DATA_ROOM_REQUIREMENT',id,existing||{},item);return json({updated:true,workspace:await workspace(context.env.DB,tenantId,round)});}
  if(action==='save-document'){const existing=body.item?.id?await first(context.env.DB,'SELECT * FROM fundraising_data_room_documents WHERE tenant_id=? AND round_id=? AND id=? LIMIT 1',[tenantId,round.id,body.item.id]):null;const item=sanitizeDocument(body.item||{},existing||{});if(!item.title)return error('Document title is required',422);if(item.requirementId&&!await first(context.env.DB,'SELECT id FROM fundraising_data_room_requirements WHERE tenant_id=? AND round_id=? AND id=? LIMIT 1',[tenantId,round.id,item.requirementId]))return error('Mapped document requirement was not found in this round',404);const now=nowIso(),id=existing?.id||makeId('drd'),nextVersion=existing?Number(existing.current_version_number||0)+1:1;if(existing){await run(context.env.DB,'UPDATE fundraising_data_room_documents SET requirement_id=?,category=?,title=?,confidentiality=?,status=?,current_version_number=?,notes=?,updated_at=?,updated_by=? WHERE tenant_id=? AND round_id=? AND id=?',[item.requirementId||null,item.category,item.title,item.confidentiality,item.status,nextVersion,item.notes||null,now,auth.userId,tenantId,round.id,id]);}else await run(context.env.DB,'INSERT INTO fundraising_data_room_documents(id,tenant_id,project_id,round_id,requirement_id,category,title,confidentiality,status,current_version_number,notes,created_at,updated_at,created_by,updated_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',[id,tenantId,round.project_id,round.id,item.requirementId||null,item.category,item.title,item.confidentiality,item.status,nextVersion,item.notes||null,now,now,auth.userId,auth.userId]);const versionId=makeId('drv');await run(context.env.DB,`INSERT INTO fundraising_data_room_document_versions(id,tenant_id,document_id,version_number,version_label,secure_url,file_name,mime_type,size_bytes,checksum,change_note,uploaded_by_source,created_at,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,[versionId,tenantId,id,nextVersion,item.versionLabel||`v${nextVersion}`,item.secureUrl,item.fileName||null,item.mimeType||null,item.sizeBytes,item.checksum||null,item.changeNote||null,'INTERNAL',now,auth.userId]);if(item.requirementId)await run(context.env.DB,"UPDATE fundraising_data_room_requirements SET status='UPLOADED',updated_at=?,updated_by=? WHERE tenant_id=? AND round_id=? AND id=? AND status NOT IN ('VERIFIED','NOT_APPLICABLE')",[now,auth.userId,tenantId,round.id,item.requirementId]);await activity(context.env.DB,auth,round,existing?'DOCUMENT_VERSION_ADDED':'DOCUMENT_UPLOADED',{documentId:id,versionId,metadata:{version:nextVersion}});await audit(context.env.DB,auth,existing?'DATA_ROOM_DOCUMENT_VERSION_ADDED':'DATA_ROOM_DOCUMENT_CREATED','DATA_ROOM_DOCUMENT',id,existing||{},item);return json({updated:true,documentId:id,versionId,workspace:await workspace(context.env.DB,tenantId,round)});}
  if(action==='save-access'){const ref=text(body.item?.investorPipelineId||body.item?.targetId,120);if(!ref)return error('Investor target is required',422);const existing=await first(context.env.DB,'SELECT * FROM fundraising_data_room_access WHERE tenant_id=? AND round_id=? AND investor_pipeline_id=? LIMIT 1',[tenantId,round.id,ref]);const item=sanitizeAccess({...body.item,investorPipelineId:ref},existing||{}),now=nowIso(),id=existing?.id||makeId('dra'),revoked=['REVOKED','EXPIRED'].includes(item.accessStatus);if(existing)await run(context.env.DB,'UPDATE fundraising_data_room_access SET nda_status=?,access_status=?,allowed_categories_json=?,granted_at=?,expires_at=?,revoked_at=?,revoke_reason=?,notes=?,updated_at=?,updated_by=? WHERE tenant_id=? AND round_id=? AND id=?',[item.ndaStatus,item.accessStatus,JSON.stringify(item.allowedCategories),item.accessStatus==='GRANTED'?(existing.granted_at||now):existing.granted_at,item.expiresAt||null,revoked?now:null,item.revokeReason||null,item.notes||null,now,auth.userId,tenantId,round.id,id]);else await run(context.env.DB,'INSERT INTO fundraising_data_room_access(id,tenant_id,project_id,round_id,investor_pipeline_id,nda_status,access_status,allowed_categories_json,granted_at,expires_at,revoked_at,revoke_reason,notes,created_at,updated_at,created_by,updated_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',[id,tenantId,round.project_id,round.id,ref,item.ndaStatus,item.accessStatus,JSON.stringify(item.allowedCategories),item.accessStatus==='GRANTED'?now:null,item.expiresAt||null,revoked?now:null,item.revokeReason||null,item.notes||null,now,now,auth.userId,auth.userId]);if(item.accessStatus==='GRANTED'&&existing?.access_status!=='GRANTED')await activity(context.env.DB,auth,round,'ACCESS_GRANTED',{accessId:id,investorPipelineId:ref});if(revoked&&existing?.access_status!==item.accessStatus)await activity(context.env.DB,auth,round,item.accessStatus==='EXPIRED'?'ACCESS_EXPIRED':'ACCESS_REVOKED',{accessId:id,investorPipelineId:ref,metadata:{reason:item.revokeReason||''}});await audit(context.env.DB,auth,existing?'DATA_ROOM_ACCESS_UPDATED':'DATA_ROOM_ACCESS_CREATED','DATA_ROOM_ACCESS',id,existing||{},item);return json({updated:true,workspace:await workspace(context.env.DB,tenantId,round)});}
  if(action==='save-diligence'){const existing=body.item?.id?await first(context.env.DB,'SELECT * FROM fundraising_diligence_requests WHERE tenant_id=? AND round_id=? AND id=? LIMIT 1',[tenantId,round.id,body.item.id]):null;const item=sanitizeDiligence(body.item||{},existing||{});if(!item.title)return error('Diligence request title is required',422);if(item.ownerUserId&&!await member(context.env.DB,tenantId,item.ownerUserId))return error('Diligence owner is not an active workspace member',422);for(const id of item.documentIds){if(!await first(context.env.DB,'SELECT id FROM fundraising_data_room_documents WHERE tenant_id=? AND round_id=? AND id=? LIMIT 1',[tenantId,round.id,id]))return error('A mapped diligence document was not found in this round',404);}const now=nowIso(),id=existing?.id||makeId('dd'),resolved=['RESOLVED','CLOSED'].includes(item.status);if(existing)await run(context.env.DB,'UPDATE fundraising_diligence_requests SET investor_pipeline_id=?,title=?,category=?,status=?,owner_user_id=?,due_date=?,founder_response=?,internal_notes=?,resolved_at=?,updated_at=?,updated_by=? WHERE tenant_id=? AND round_id=? AND id=?',[item.investorPipelineId||null,item.title,item.category,item.status,item.ownerUserId||null,item.dueDate||null,item.founderResponse||null,item.internalNotes||null,resolved?(existing.resolved_at||now):null,now,auth.userId,tenantId,round.id,id]);else await run(context.env.DB,'INSERT INTO fundraising_diligence_requests(id,tenant_id,project_id,round_id,investor_pipeline_id,title,category,status,owner_user_id,due_date,founder_response,internal_notes,resolved_at,created_at,updated_at,created_by,updated_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',[id,tenantId,round.project_id,round.id,item.investorPipelineId||null,item.title,item.category,item.status,item.ownerUserId||null,item.dueDate||null,item.founderResponse||null,item.internalNotes||null,resolved?now:null,now,now,auth.userId,auth.userId]);await run(context.env.DB,'DELETE FROM fundraising_diligence_request_documents WHERE tenant_id=? AND request_id=?',[tenantId,id]);for(const documentId of item.documentIds)await run(context.env.DB,'INSERT INTO fundraising_diligence_request_documents(tenant_id,request_id,document_id,created_at,created_by) VALUES(?,?,?,?,?)',[tenantId,id,documentId,now,auth.userId]);await activity(context.env.DB,auth,round,resolved?'DILIGENCE_RESOLVED':existing?'DILIGENCE_RESPONDED':'DILIGENCE_REQUESTED',{investorPipelineId:item.investorPipelineId||null,metadata:{requestId:id}});await audit(context.env.DB,auth,existing?'DILIGENCE_REQUEST_UPDATED':'DILIGENCE_REQUEST_CREATED','DILIGENCE_REQUEST',id,existing||{},item);return json({updated:true,workspace:await workspace(context.env.DB,tenantId,round)});}
  if(action==='record-document-activity'){const eventType=text(body.eventType,80).toUpperCase();if(!['DOCUMENT_VIEWED','DOCUMENT_DOWNLOADED'].includes(eventType))return error('Document activity type is invalid',422);const doc=await first(context.env.DB,'SELECT id,current_version_number FROM fundraising_data_room_documents WHERE tenant_id=? AND round_id=? AND id=? LIMIT 1',[tenantId,round.id,text(body.documentId,120)]);if(!doc)return error('Data room document was not found',404);const version=await first(context.env.DB,'SELECT id FROM fundraising_data_room_document_versions WHERE tenant_id=? AND document_id=? AND version_number=? LIMIT 1',[tenantId,doc.id,doc.current_version_number]);await activity(context.env.DB,auth,round,eventType,{documentId:doc.id,versionId:version?.id||null,investorPipelineId:text(body.investorPipelineId,120)||null});return json({recorded:true});}
  return error('Data Room action is not supported',404);
}catch(cause){console.error('R72 data room write failed',cause);return error(cause.message||'Data Room update failed',Number(cause.status||500));}}
