import { json,error,readJson } from '../../../../lib/response.js';
import { all,first,run,makeId,nowIso } from '../../../../lib/db.js';
import { requireTenant } from '../../../../lib/permissions.js';
import { requirePortalProject } from '../../../../lib/portal-access.js';
import { sanitizeDocument,safeHttpsUrl,jsonList } from '../../../../lib/data-room-r72.js';

const MISSING_SCHEMA=/(no such table.*fundraising_data_room|D1_ERROR.*fundraising_data_room|SQLITE_ERROR.*fundraising_data_room)/i;
const text=(value,max=8000)=>String(value??'').trim().slice(0,max);
async function ensureSchema(db){try{await first(db,'SELECT id FROM fundraising_data_room_documents LIMIT 1');}catch(cause){if(MISSING_SCHEMA.test(String(cause?.message||''))){const e=new Error('Founder Data Room is not available until migration 0005 is applied');e.status=503;throw e;}throw cause;}}
async function roundForProject(db,tenantId,projectId,roundId=''){if(roundId)return first(db,'SELECT * FROM fundraising_rounds WHERE tenant_id=? AND project_id=? AND id=? LIMIT 1',[tenantId,projectId,roundId]);return first(db,"SELECT * FROM fundraising_rounds WHERE tenant_id=? AND project_id=? ORDER BY CASE WHEN stage IN ('CLOSED','PAUSED') THEN 1 ELSE 0 END,updated_at DESC LIMIT 1",[tenantId,projectId]);}
async function requirements(db,tenantId,roundId){return all(db,'SELECT id,category,requirement_key,title,required,status,notes,updated_at FROM fundraising_data_room_requirements WHERE tenant_id=? AND round_id=? ORDER BY category,title',[tenantId,roundId]);}
async function documents(db,tenantId,roundId){const docs=await all(db,"SELECT id,requirement_id,category,title,confidentiality,status,current_version_number,notes,updated_at FROM fundraising_data_room_documents WHERE tenant_id=? AND round_id=? AND status='ACTIVE' ORDER BY category,title",[tenantId,roundId]);if(!docs.length)return[];const marks=docs.map(()=>'?').join(',');const versions=await all(db,`SELECT id,document_id,version_number,version_label,secure_url,file_name,mime_type,size_bytes,change_note,uploaded_by_source,created_at FROM fundraising_data_room_document_versions WHERE tenant_id=? AND document_id IN (${marks}) ORDER BY document_id,version_number DESC`,[tenantId,...docs.map(x=>x.id)]);return docs.map(doc=>({...doc,versions:versions.filter(v=>v.document_id===doc.id),current_version:versions.find(v=>v.document_id===doc.id&&Number(v.version_number)===Number(doc.current_version_number))||null}));}
async function diligence(db,tenantId,roundId){const rows=await all(db,"SELECT id,title,category,status,due_date,founder_response,updated_at FROM fundraising_diligence_requests WHERE tenant_id=? AND round_id=? AND status NOT IN ('CLOSED') ORDER BY CASE status WHEN 'WAITING_FOUNDER' THEN 0 WHEN 'OPEN' THEN 1 WHEN 'IN_PROGRESS' THEN 2 ELSE 3 END,due_date,updated_at DESC",[tenantId,roundId]);if(!rows.length)return[];const marks=rows.map(()=>'?').join(',');const links=await all(db,`SELECT request_id,document_id FROM fundraising_diligence_request_documents WHERE tenant_id=? AND request_id IN (${marks})`,[tenantId,...rows.map(x=>x.id)]);return rows.map(row=>({...row,document_ids:links.filter(x=>x.request_id===row.id).map(x=>x.document_id)}));}
async function activity(db,auth,round,eventType,meta={}){await run(db,`INSERT INTO fundraising_data_room_activity(id,tenant_id,project_id,round_id,document_id,version_id,actor_user_id,event_type,occurred_at,metadata_json) VALUES(?,?,?,?,?,?,?,?,?,?)`,[makeId('dra'),auth.tenantId,round.project_id,round.id,meta.documentId||null,meta.versionId||null,auth.userId,eventType,nowIso(),JSON.stringify(meta.metadata||{})]);}
async function audit(db,auth,action,entityId,before,after){await run(db,`INSERT INTO audit_logs(id,tenant_id,user_id,action,entity_type,entity_id,before_data,after_data,created_at) VALUES(?,?,?,?,?,?,?,?,?)`,[makeId('aud'),auth.tenantId,auth.userId,action,'FOUNDER_DATA_ROOM',entityId,JSON.stringify(before||{}),JSON.stringify(after||{}),nowIso()]);}
async function payload(db,tenantId,round){const [reqs,docs,requests]=await Promise.all([requirements(db,tenantId,round.id),documents(db,tenantId,round.id),diligence(db,tenantId,round.id)]);return{round:{id:round.id,projectId:round.project_id,roundName:round.round_name,stage:round.stage},requirements:reqs,documents:docs,diligence:requests,summary:{documents:docs.length,missing:reqs.filter(x=>x.required&&['MISSING','REQUESTED'].includes(x.status)).length,waitingFounder:requests.filter(x=>x.status==='WAITING_FOUNDER').length}};}

export async function onRequestGet(context){try{const auth=context.data.auth;requireTenant(auth);if(auth.role!=='EXTERNAL_COLLABORATOR')return error('External portal access is required',403);if(!context.env.DB)return error('D1 binding DB is not configured',500);const projectId=String(context.params.id||''),access=await requirePortalProject(context.env.DB,auth,projectId,'viewDocuments');if(access.grant.portalType!=='FOUNDER')return error('Founder portal access is required',403);await ensureSchema(context.env.DB);const url=new URL(context.request.url),round=await roundForProject(context.env.DB,auth.tenantId,projectId,text(url.searchParams.get('roundId'),120));if(!round)return json({round:null,requirements:[],documents:[],diligence:[],summary:{documents:0,missing:0,waitingFounder:0},permissions:{canUpload:false,canAnswer:false}});return json({...await payload(context.env.DB,auth.tenantId,round),permissions:{canUpload:Boolean(access.grant.permissions.viewDocuments),canAnswer:Boolean(access.grant.permissions.answerDiligence)}});}catch(cause){return error(cause.message||'Founder Data Room could not be loaded',Number(cause.status||500));}}

export async function onRequestPatch(context){try{const auth=context.data.auth;requireTenant(auth);if(auth.role!=='EXTERNAL_COLLABORATOR')return error('External portal access is required',403);if(!context.env.DB)return error('D1 binding DB is not configured',500);const projectId=String(context.params.id||''),access=await requirePortalProject(context.env.DB,auth,projectId,'viewDocuments');if(access.grant.portalType!=='FOUNDER')return error('Founder portal access is required',403);await ensureSchema(context.env.DB);const body=await readJson(context.request),action=text(body.action,80).toUpperCase(),round=await roundForProject(context.env.DB,auth.tenantId,projectId,text(body.roundId,120));if(!round)return error('Founder Capital Room was not found for this project',404);
  if(action==='UPLOAD_DOCUMENT'){
    const requirementId=text(body.item?.requirementId,120);if(requirementId&&!await first(context.env.DB,'SELECT id FROM fundraising_data_room_requirements WHERE tenant_id=? AND project_id=? AND round_id=? AND id=? LIMIT 1',[auth.tenantId,projectId,round.id,requirementId]))return error('Data Room requirement was not found in this project',404);
    let existing=null;if(body.item?.id)existing=await first(context.env.DB,'SELECT * FROM fundraising_data_room_documents WHERE tenant_id=? AND project_id=? AND round_id=? AND id=? LIMIT 1',[auth.tenantId,projectId,round.id,text(body.item.id,120)]);const item=sanitizeDocument(body.item||{},existing||{});if(!item.title||!item.secureUrl)return error('Document title and secure HTTPS link are required',422);const now=nowIso(),id=existing?.id||makeId('drd'),nextVersion=existing?Number(existing.current_version_number||0)+1:1;if(existing)await run(context.env.DB,'UPDATE fundraising_data_room_documents SET requirement_id=?,category=?,title=?,confidentiality=?,current_version_number=?,notes=?,updated_at=?,updated_by=? WHERE tenant_id=? AND project_id=? AND round_id=? AND id=?',[requirementId||null,item.category,item.title,item.confidentiality,nextVersion,item.notes||null,now,auth.userId,auth.tenantId,projectId,round.id,id]);else await run(context.env.DB,"INSERT INTO fundraising_data_room_documents(id,tenant_id,project_id,round_id,requirement_id,category,title,confidentiality,status,current_version_number,notes,created_at,updated_at,created_by,updated_by) VALUES(?,?,?,?,?,?,?,?, 'ACTIVE',?,?,?,?,?,?)",[id,auth.tenantId,projectId,round.id,requirementId||null,item.category,item.title,item.confidentiality,nextVersion,item.notes||null,now,now,auth.userId,auth.userId]);const versionId=makeId('drv');await run(context.env.DB,'INSERT INTO fundraising_data_room_document_versions(id,tenant_id,document_id,version_number,version_label,secure_url,file_name,mime_type,size_bytes,checksum,change_note,uploaded_by_source,created_at,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)',[versionId,auth.tenantId,id,nextVersion,item.versionLabel||`v${nextVersion}`,safeHttpsUrl(item.secureUrl),item.fileName||null,item.mimeType||null,item.sizeBytes,item.checksum||null,item.changeNote||null,'FOUNDER_PORTAL',now,auth.userId]);if(requirementId)await run(context.env.DB,"UPDATE fundraising_data_room_requirements SET status='UPLOADED',updated_at=?,updated_by=? WHERE tenant_id=? AND project_id=? AND round_id=? AND id=? AND status NOT IN ('VERIFIED','NOT_APPLICABLE')",[now,auth.userId,auth.tenantId,projectId,round.id,requirementId]);await activity(context.env.DB,auth,round,existing?'DOCUMENT_VERSION_ADDED':'DOCUMENT_UPLOADED',{documentId:id,versionId,metadata:{source:'FOUNDER_PORTAL'}});await audit(context.env.DB,auth,existing?'FOUNDER_DOCUMENT_VERSION_ADDED':'FOUNDER_DOCUMENT_UPLOADED',id,existing||{},{title:item.title,category:item.category,requirementId,version:nextVersion});return json({updated:true,workspace:await payload(context.env.DB,auth.tenantId,round)});
  }
  if(action==='ANSWER_DILIGENCE'){
    if(!access.grant.permissions.answerDiligence)return error('Founder diligence response permission is not enabled',403);const request=await first(context.env.DB,'SELECT * FROM fundraising_diligence_requests WHERE tenant_id=? AND project_id=? AND round_id=? AND id=? LIMIT 1',[auth.tenantId,projectId,round.id,text(body.requestId,120)]);if(!request)return error('Diligence request was not found in this project',404);if(['RESOLVED','CLOSED'].includes(request.status))return error('Resolved diligence requests cannot be changed from the Founder Portal',409);const response=text(body.response,8000);if(!response)return error('Founder response is required',422);const documentIds=Array.isArray(body.documentIds)?body.documentIds.map(x=>text(x,120)).filter(Boolean).slice(0,50):[];for(const documentId of documentIds){if(!await first(context.env.DB,"SELECT id FROM fundraising_data_room_documents WHERE tenant_id=? AND project_id=? AND round_id=? AND id=? AND status='ACTIVE' LIMIT 1",[auth.tenantId,projectId,round.id,documentId]))return error('A linked Data Room document was not found in this project',404);}const now=nowIso();await run(context.env.DB,"UPDATE fundraising_diligence_requests SET founder_response=?,status='IN_PROGRESS',updated_at=?,updated_by=? WHERE tenant_id=? AND project_id=? AND round_id=? AND id=?",[response,now,auth.userId,auth.tenantId,projectId,round.id,request.id]);await run(context.env.DB,'DELETE FROM fundraising_diligence_request_documents WHERE tenant_id=? AND request_id=?',[auth.tenantId,request.id]);for(const documentId of documentIds)await run(context.env.DB,'INSERT INTO fundraising_diligence_request_documents(tenant_id,request_id,document_id,created_at,created_by) VALUES(?,?,?,?,?)',[auth.tenantId,request.id,documentId,now,auth.userId]);await activity(context.env.DB,auth,round,'DILIGENCE_RESPONDED',{metadata:{requestId:request.id,linkedDocuments:documentIds.length}});await audit(context.env.DB,auth,'FOUNDER_DILIGENCE_RESPONDED',request.id,{status:request.status},{status:'IN_PROGRESS',response,documentIds});return json({updated:true,workspace:await payload(context.env.DB,auth.tenantId,round)});
  }
  if(action==='RECORD_DOCUMENT_ACTIVITY'){
    const eventType=text(body.eventType,80).toUpperCase();if(!['DOCUMENT_VIEWED','DOCUMENT_DOWNLOADED'].includes(eventType))return error('Document activity type is invalid',422);const doc=await first(context.env.DB,"SELECT id,current_version_number FROM fundraising_data_room_documents WHERE tenant_id=? AND project_id=? AND round_id=? AND id=? AND status='ACTIVE' LIMIT 1",[auth.tenantId,projectId,round.id,text(body.documentId,120)]);if(!doc)return error('Data Room document was not found in this project',404);const version=await first(context.env.DB,'SELECT id FROM fundraising_data_room_document_versions WHERE tenant_id=? AND document_id=? AND version_number=? LIMIT 1',[auth.tenantId,doc.id,doc.current_version_number]);await activity(context.env.DB,auth,round,eventType,{documentId:doc.id,versionId:version?.id||null,metadata:{source:'FOUNDER_PORTAL'}});return json({recorded:true});
  }
  return error('Founder Data Room action is not supported',422);
}catch(cause){return error(cause.message||'Founder Data Room update failed',Number(cause.status||500));}}
