import { json,error,readJson } from '../../../../lib/response.js';
import { all,first,run,makeId,nowIso } from '../../../../lib/db.js';
import { requireTenant } from '../../../../lib/permissions.js';
import { requirePortalProject } from '../../../../lib/portal-access.js';
import { FOUNDER_ONBOARDING_KEYS,normalizeOnboardingItem,sanitizeOnboardingItem,onboardingReadiness,publicOnboardingItem } from '../../../../lib/founder-onboarding.js';

const MISSING_SCHEMA=/(no such table.*founder_onboarding_items|D1_ERROR.*founder_onboarding_items|SQLITE_ERROR.*founder_onboarding_items)/i;
const text=(value,max=8000)=>String(value??'').trim().slice(0,max);
const number=(value)=>Math.max(0,Number(value||0));

async function ensureSchema(db){try{await first(db,'SELECT id FROM founder_onboarding_items LIMIT 1');}catch(cause){if(MISSING_SCHEMA.test(String(cause?.message||''))){const e=new Error('Founder onboarding is not available until migration 0004 is applied');e.status=503;throw e;}throw cause;}}
async function projectRound(db,tenantId,projectId,roundId=''){
  if(roundId)return first(db,`SELECT r.*,p.name AS project_name,p.region AS project_region,p.country AS project_country,p.website AS project_website FROM fundraising_rounds r JOIN projects p ON p.id=r.project_id AND p.tenant_id=r.tenant_id WHERE r.tenant_id=? AND r.project_id=? AND r.id=? LIMIT 1`,[tenantId,projectId,roundId]);
  return first(db,`SELECT r.*,p.name AS project_name,p.region AS project_region,p.country AS project_country,p.website AS project_website FROM fundraising_rounds r JOIN projects p ON p.id=r.project_id AND p.tenant_id=r.tenant_id WHERE r.tenant_id=? AND r.project_id=? ORDER BY CASE WHEN r.stage IN ('CLOSED','PAUSED') THEN 1 ELSE 0 END,r.updated_at DESC LIMIT 1`,[tenantId,projectId]);
}
async function rowsForRound(db,tenantId,roundId){return all(db,'SELECT * FROM founder_onboarding_items WHERE tenant_id=? AND round_id=? ORDER BY item_key',[tenantId,roundId]);}
function projectShape(round){return {id:round.project_id,name:round.project_name,region:round.project_region,country:round.project_country,website:round.project_website};}
function safeRound(round){return {id:round.id,projectId:round.project_id,roundName:round.round_name,stage:round.stage,instrument:round.instrument||'',fundingStage:round.funding_stage||'',currency:round.currency||'USD',targetAmount:Number(round.target_amount||0),valuation:Number(round.valuation||0),targetCloseDate:round.target_close_date||null,readinessScore:Number(round.readiness_score||0)};}
async function build(db,tenantId,round){const rows=await rowsForRound(db,tenantId,round.id),project=projectShape(round),readiness=onboardingReadiness(rows,round,project),map=new Map(rows.map(row=>[row.item_key,publicOnboardingItem(row)]));return {round:safeRound(round),readiness:{score:readiness.score,complete:readiness.complete,applicable:readiness.applicable,total:readiness.total},items:FOUNDER_ONBOARDING_KEYS.map(key=>{const check=readiness.checks.find(item=>item.key===key);const item=map.get(key)||{key,status:'NOT_STARTED',data:{},evidenceUrl:'',notes:'',completedAt:null,updatedAt:null};return {...item,status:check?.status||item.status,complete:Boolean(check?.complete),applicable:check?.applicable!==false,weight:check?.weight||0};})};}
async function audit(db,auth,action,entityId,before,after){await run(db,`INSERT INTO audit_logs(id,tenant_id,user_id,action,entity_type,entity_id,before_data,after_data,created_at) VALUES(?,?,?,?,?,?,?,?,?)`,[makeId('aud'),auth.tenantId,auth.userId,action,'FOUNDER_ONBOARDING',entityId,JSON.stringify(before||{}),JSON.stringify(after||{}),nowIso()]);}

export async function onRequestGet(context){
  try{const auth=context.data.auth;requireTenant(auth);if(auth.role!=='EXTERNAL_COLLABORATOR')return error('External portal access is required',403);if(!context.env.DB)return error('D1 binding DB is not configured',500);const projectId=String(context.params.id||'');const access=await requirePortalProject(context.env.DB,auth,projectId,'viewFundraising');if(access.grant.portalType!=='FOUNDER')return error('Founder portal access is required',403);await ensureSchema(context.env.DB);const url=new URL(context.request.url),round=await projectRound(context.env.DB,auth.tenantId,projectId,text(url.searchParams.get('roundId'),120));if(!round)return json({round:null,readiness:{score:0,complete:0,applicable:0,total:FOUNDER_ONBOARDING_KEYS.length},items:[],permissions:{canUpdate:Boolean(access.grant.permissions.updateOnboarding)}});return json({...await build(context.env.DB,auth.tenantId,round),permissions:{canUpdate:Boolean(access.grant.permissions.updateOnboarding)}});}
  catch(cause){return error(cause.message||'Founder onboarding could not be loaded',Number(cause.status||500));}
}

export async function onRequestPatch(context){
  try{
    const auth=context.data.auth;requireTenant(auth);if(auth.role!=='EXTERNAL_COLLABORATOR')return error('External portal access is required',403);if(!context.env.DB)return error('D1 binding DB is not configured',500);const projectId=String(context.params.id||'');const access=await requirePortalProject(context.env.DB,auth,projectId,'updateOnboarding');if(access.grant.portalType!=='FOUNDER')return error('Founder portal access is required',403);await ensureSchema(context.env.DB);
    const body=await readJson(context.request),action=text(body.action,80).toUpperCase();if(action!=='SAVE_ONBOARDING_ITEM')return error('Portal onboarding action is not supported',422);const round=await projectRound(context.env.DB,auth.tenantId,projectId,text(body.roundId,120));if(!round)return error('Founder Capital Room was not found for this project',404);const key=String(body.item?.key||'').toUpperCase();if(!FOUNDER_ONBOARDING_KEYS.includes(key))return error('Founder onboarding item is invalid',422);
    const existing=await first(context.env.DB,'SELECT * FROM founder_onboarding_items WHERE tenant_id=? AND project_id=? AND round_id=? AND item_key=? LIMIT 1',[auth.tenantId,projectId,round.id,key]);let workingRound={...round};
    if(key==='RAISE'){
      const data=body.item?.data||{},targetAmount=number(data.targetAmount??round.target_amount),valuation=number(data.valuation??round.valuation),instrument=text(data.instrument??round.instrument,100),fundingStage=text(data.fundingStage??round.funding_stage,100);if(!instrument&&targetAmount>0)return error('Fundraising instrument is required when a raise target is configured',422);await run(context.env.DB,'UPDATE fundraising_rounds SET target_amount=?,valuation=?,instrument=?,funding_stage=?,updated_at=?,updated_by=? WHERE tenant_id=? AND project_id=? AND id=?',[targetAmount,valuation,instrument||null,fundingStage||null,nowIso(),auth.userId,auth.tenantId,projectId,round.id]);workingRound={...workingRound,target_amount:targetAmount,valuation,instrument,funding_stage:fundingStage};
    }
    const item=sanitizeOnboardingItem({...(body.item||{}),key},existing||{},workingRound,projectShape(workingRound)),now=nowIso(),id=existing?.id||makeId('fonb');
    if(existing)await run(context.env.DB,'UPDATE founder_onboarding_items SET status=?,data_json=?,evidence_url=?,notes=?,completed_at=?,updated_at=?,updated_by=? WHERE tenant_id=? AND project_id=? AND id=?',[item.status,JSON.stringify(item.data),item.evidenceUrl||null,item.notes||null,item.complete?existing.completed_at||now:null,now,auth.userId,auth.tenantId,projectId,id]);
    else await run(context.env.DB,'INSERT INTO founder_onboarding_items(id,tenant_id,project_id,round_id,item_key,status,data_json,evidence_url,notes,completed_at,created_at,updated_at,created_by,updated_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)',[id,auth.tenantId,projectId,workingRound.id,key,item.status,JSON.stringify(item.data),item.evidenceUrl||null,item.notes||null,item.complete?now:null,now,now,auth.userId,auth.userId]);
    const rows=await rowsForRound(context.env.DB,auth.tenantId,workingRound.id),readiness=onboardingReadiness(rows,workingRound,projectShape(workingRound));await run(context.env.DB,'UPDATE fundraising_rounds SET readiness_score=?,updated_at=?,updated_by=? WHERE tenant_id=? AND project_id=? AND id=?',[readiness.score,nowIso(),auth.userId,auth.tenantId,projectId,workingRound.id]);await audit(context.env.DB,auth,existing?'PORTAL_FOUNDER_ONBOARDING_UPDATED':'PORTAL_FOUNDER_ONBOARDING_CREATED',id,existing?normalizeOnboardingItem(existing):{}, {...item,key,roundId:workingRound.id,projectId,readinessScore:readiness.score});const refreshed=await projectRound(context.env.DB,auth.tenantId,projectId,workingRound.id);return json({updated:true,workspace:await build(context.env.DB,auth.tenantId,refreshed)});
  }catch(cause){return error(cause.message||'Founder onboarding update failed',Number(cause.status||500));}
}
