import {json,error,readJson} from '../../lib/response.js';
import {all,first,run,makeId,nowIso} from '../../lib/db.js';
import {requireTenant} from '../../lib/permissions.js';
import {normalizeAgreementInput,requiredReviewTypes,agreementSummary,assertAgreementApproval,assertAgreementSignature,assertAgreementActivation,sanitizeReview,issue} from '../../lib/agreements-compliance.js';

const WRITE_ROLES=new Set(['OWNER','ADMIN','BD_MANAGER']);
const FINAL_ROLES=new Set(['OWNER','ADMIN']);
const text=(value,max=5000)=>String(value??'').trim().slice(0,max)||null;
const upper=(value)=>String(value??'').trim().toUpperCase();
async function ensureSchema(db){const row=await first(db,"SELECT name FROM sqlite_master WHERE type='table' AND name='agreements' LIMIT 1",[]);if(!row)throw issue('Agreement Registry migration 0003 must be applied before this module is available',503);}
async function loadAgreement(db,tenantId,id){const agreement=await first(db,`SELECT a.*,p.name AS project_name,o.name AS opportunity_name,c.name AS campaign_name,par.name AS partner_name,fr.round_name,u.full_name AS owner_name FROM agreements a JOIN projects p ON p.id=a.project_id AND p.tenant_id=a.tenant_id LEFT JOIN opportunities o ON o.id=a.opportunity_id AND o.tenant_id=a.tenant_id LEFT JOIN campaigns c ON c.id=a.campaign_id AND c.tenant_id=a.tenant_id LEFT JOIN partners par ON par.id=a.partner_id AND par.tenant_id=a.tenant_id LEFT JOIN fundraising_rounds fr ON fr.id=a.fundraising_round_id AND fr.tenant_id=a.tenant_id LEFT JOIN users u ON u.id=a.owner_user_id WHERE a.tenant_id=? AND a.id=? LIMIT 1`,[tenantId,id]);if(!agreement)return null;const reviews=await all(db,`SELECT r.*,u.full_name AS reviewer_name FROM agreement_reviews r LEFT JOIN users u ON u.id=r.reviewer_user_id WHERE r.tenant_id=? AND r.agreement_id=? ORDER BY r.review_type`,[tenantId,id]);return{agreement,reviews,summary:agreementSummary(agreement,reviews)};}
async function audit(db,tenantId,userId,action,id,beforeData,afterData){await run(db,`INSERT INTO audit_logs(id,tenant_id,user_id,action,entity_type,entity_id,before_data,after_data,created_at) VALUES(?,?,?,?,?,?,?,?,?)`,[makeId('aud'),tenantId,userId,action,'AGREEMENT',id,JSON.stringify(beforeData||{}),JSON.stringify(afterData||{}),nowIso()]);}
async function validateOwner(db,tenantId,userId){if(!userId)return null;const member=await first(db,"SELECT tm.user_id FROM tenant_memberships tm JOIN users u ON u.id=tm.user_id WHERE tm.tenant_id=? AND tm.user_id=? AND tm.status='ACTIVE' AND u.status='ACTIVE' LIMIT 1",[tenantId,userId]);if(!member)throw issue('Agreement owner must be an active member of this workspace',422);return userId;}
async function syncRequiredReviews(db,tenantId,id,agreement,auth){const now=nowIso();for(const reviewType of requiredReviewTypes(agreement)){await run(db,`INSERT INTO agreement_reviews(id,tenant_id,agreement_id,review_type,status,created_at,updated_at,created_by,updated_by) VALUES(?,?,?,?, 'NOT_STARTED',?,?,?,?) ON CONFLICT(tenant_id,agreement_id,review_type) DO NOTHING`,[makeId('agrv'),tenantId,id,reviewType,now,now,auth.userId,auth.userId]);}}
async function mirrorPartner(db,tenantId,agreement){if(!agreement.partner_id)return;const status=['SIGNED','ACTIVE'].includes(agreement.status)?agreement.status:agreement.status==='TERMINATED'?'TERMINATED':agreement.status==='EXPIRED'?'EXPIRED':null;if(!status)return;await run(db,'UPDATE partners SET agreement_status=?,agreement_url=COALESCE(?,agreement_url),updated_at=? WHERE tenant_id=? AND id=?',[status,agreement.signed_document_url,nowIso(),tenantId,agreement.partner_id]);}
function requireWrite(auth){if(!WRITE_ROLES.has(auth?.role))throw issue('Owner, Admin or BD Manager permission is required',403);}
function requireFinal(auth){if(!FINAL_ROLES.has(auth?.role))throw issue('Owner or Admin permission is required',403);}

export async function onRequestGet(context){try{const auth=context.data.auth,tenantId=requireTenant(auth);if(!context.env.DB)return error('D1 binding DB is not configured',500);await ensureSchema(context.env.DB);const item=await loadAgreement(context.env.DB,tenantId,context.params.id);if(!item)return error('Agreement not found',404);return json({item,permissions:{canWrite:WRITE_ROLES.has(auth.role),canFinalise:FINAL_ROLES.has(auth.role)},methodology:{version:'R70-1',governanceTrackingOnly:true,legalDetermination:false}});}catch(cause){return error(cause.message||'Agreement could not be loaded',Number(cause.status||500));}}

export async function onRequestPatch(context){try{const auth=context.data.auth;requireWrite(auth);const tenantId=requireTenant(auth);if(!context.env.DB)return json({updated:true,demo:true});await ensureSchema(context.env.DB);const before=await loadAgreement(context.env.DB,tenantId,context.params.id);if(!before)return error('Agreement not found',404);const body=await readJson(context.request),action=upper(body.action),id=before.agreement.id,now=nowIso();let auditAction='AGREEMENT_UPDATED';
  if(action==='UPDATE_DRAFT'){
    if(before.agreement.status!=='DRAFT')throw issue('Only a Draft agreement can be edited. Return it to Draft first.',409);const input=normalizeAgreementInput({...before.agreement,...body,agreementType:body.agreementType||before.agreement.agreement_type,counterpartyName:body.counterpartyName||before.agreement.counterparty_name});const owner=await validateOwner(context.env.DB,tenantId,text(body.ownerUserId,120)||before.agreement.owner_user_id);
    await run(context.env.DB,`UPDATE agreements SET agreement_type=?,title=?,counterparty_name=?,owner_user_id=?,jurisdiction=?,governing_law_note=?,scope_summary=?,currency=?,retainer_amount=?,success_fee_percentage=?,success_fee_note=?,exclusivity=?,confidentiality_required=?,conflict_review_required=?,privacy_review_required=?,compliance_review_required=?,start_date=?,end_date=?,renewal_date=?,notes=?,updated_at=?,updated_by=? WHERE tenant_id=? AND id=?`,[input.agreementType,input.title,input.counterpartyName,owner,input.jurisdiction,input.governingLawNote,input.scopeSummary,input.currency,input.retainerAmount,input.successFeePercentage,input.successFeeNote,input.exclusivity,input.confidentialityRequired?1:0,input.conflictReviewRequired?1:0,input.privacyReviewRequired?1:0,input.complianceReviewRequired?1:0,input.startDate,input.endDate,input.renewalDate,input.notes,now,auth.userId,tenantId,id]);await syncRequiredReviews(context.env.DB,tenantId,id,{...input,agreementType:input.agreementType},auth);auditAction='AGREEMENT_DRAFT_UPDATED';
  }else if(action==='SUBMIT_REVIEW'){
    if(before.agreement.status!=='DRAFT')throw issue('Only a Draft agreement can be submitted for review',409);await run(context.env.DB,"UPDATE agreements SET status='REVIEW',updated_at=?,updated_by=? WHERE tenant_id=? AND id=?",[now,auth.userId,tenantId,id]);auditAction='AGREEMENT_REVIEW_SUBMITTED';
  }else if(action==='REVIEW_UPDATE'){
    requireFinal(auth);if(!['DRAFT','REVIEW','APPROVED'].includes(before.agreement.status))throw issue('Reviews cannot be changed after the agreement is sent or signed',409);const review=sanitizeReview(body);const reviewer=await validateOwner(context.env.DB,tenantId,text(body.reviewerUserId,120)||auth.userId);await run(context.env.DB,`INSERT INTO agreement_reviews(id,tenant_id,agreement_id,review_type,status,reviewer_user_id,decision_note,evidence_reference,reviewed_at,expires_at,created_at,updated_at,created_by,updated_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(tenant_id,agreement_id,review_type) DO UPDATE SET status=excluded.status,reviewer_user_id=excluded.reviewer_user_id,decision_note=excluded.decision_note,evidence_reference=excluded.evidence_reference,reviewed_at=excluded.reviewed_at,expires_at=excluded.expires_at,updated_at=excluded.updated_at,updated_by=excluded.updated_by`,[makeId('agrv'),tenantId,id,review.reviewType,review.status,reviewer,review.decisionNote,review.evidenceReference,['CLEAR','ISSUES','BLOCKED','NOT_REQUIRED'].includes(review.status)?now:null,review.expiresAt,now,now,auth.userId,auth.userId]);if(before.agreement.status==='APPROVED'&&!['CLEAR','NOT_REQUIRED'].includes(review.status))await run(context.env.DB,"UPDATE agreements SET status='REVIEW',updated_at=?,updated_by=? WHERE tenant_id=? AND id=?",[now,auth.userId,tenantId,id]);auditAction='AGREEMENT_REVIEW_UPDATED';
  }else if(action==='APPROVE'){
    requireFinal(auth);if(before.agreement.status!=='REVIEW')throw issue('Only an agreement in Review can be approved',409);assertAgreementApproval(before.agreement,before.reviews);await run(context.env.DB,"UPDATE agreements SET status='APPROVED',updated_at=?,updated_by=? WHERE tenant_id=? AND id=?",[now,auth.userId,tenantId,id]);auditAction='AGREEMENT_APPROVED';
  }else if(action==='MARK_SENT'){
    if(before.agreement.status!=='APPROVED')throw issue('Approve the agreement before marking it sent',409);await run(context.env.DB,"UPDATE agreements SET status='SENT',sent_at=?,updated_at=?,updated_by=? WHERE tenant_id=? AND id=?",[now,now,auth.userId,tenantId,id]);auditAction='AGREEMENT_SENT';
  }else if(action==='RECORD_SIGNED'){
    if(before.agreement.status!=='SENT')throw issue('Only a sent agreement can be recorded as signed',409);const signed=assertAgreementSignature(body);await run(context.env.DB,"UPDATE agreements SET status='SIGNED',signed_at=?,signed_by_name=?,signature_method=?,signed_document_url=?,signature_evidence_reference=?,updated_at=?,updated_by=? WHERE tenant_id=? AND id=?",[signed.signedAt,signed.signedBy,signed.signatureMethod,signed.document,signed.evidence,now,auth.userId,tenantId,id]);auditAction='AGREEMENT_SIGNED';
  }else if(action==='ACTIVATE'){
    requireFinal(auth);assertAgreementActivation(before.agreement,before.reviews);await run(context.env.DB,"UPDATE agreements SET status='ACTIVE',activated_at=?,updated_at=?,updated_by=? WHERE tenant_id=? AND id=?",[now,now,auth.userId,tenantId,id]);auditAction='AGREEMENT_ACTIVATED';
  }else if(action==='RETURN_TO_DRAFT'){
    requireFinal(auth);if(!['REVIEW','APPROVED'].includes(before.agreement.status))throw issue('Only Review or Approved agreements can return to Draft',409);const reason=text(body.reason,1500);if(!reason||reason.length<5)throw issue('A reason is required to return the agreement to Draft',422);await run(context.env.DB,"UPDATE agreements SET status='DRAFT',updated_at=?,updated_by=? WHERE tenant_id=? AND id=?",[now,auth.userId,tenantId,id]);auditAction='AGREEMENT_RETURNED_TO_DRAFT';body._reason=reason;
  }else if(action==='TERMINATE'){
    requireFinal(auth);if(!['SIGNED','ACTIVE'].includes(before.agreement.status))throw issue('Only a signed or active agreement can be terminated',409);const reason=text(body.reason,3000);if(!reason||reason.length<5)throw issue('A termination reason is required',422);await run(context.env.DB,"UPDATE agreements SET status='TERMINATED',terminated_at=?,termination_reason=?,updated_at=?,updated_by=? WHERE tenant_id=? AND id=?",[now,reason,now,auth.userId,tenantId,id]);auditAction='AGREEMENT_TERMINATED';
  }else if(action==='EXPIRE'){
    requireFinal(auth);if(before.agreement.status!=='ACTIVE')throw issue('Only an active agreement can be expired',409);const today=new Date().toISOString().slice(0,10);if(!before.agreement.end_date||before.agreement.end_date>today)throw issue('Agreement end date has not been reached',409);await run(context.env.DB,"UPDATE agreements SET status='EXPIRED',updated_at=?,updated_by=? WHERE tenant_id=? AND id=?",[now,auth.userId,tenantId,id]);auditAction='AGREEMENT_EXPIRED';
  }else if(action==='CANCEL'){
    requireFinal(auth);if(!['DRAFT','REVIEW','APPROVED','SENT'].includes(before.agreement.status))throw issue('This agreement can no longer be cancelled',409);const reason=text(body.reason,2000);if(!reason||reason.length<5)throw issue('A cancellation reason is required',422);await run(context.env.DB,"UPDATE agreements SET status='CANCELLED',termination_reason=?,updated_at=?,updated_by=? WHERE tenant_id=? AND id=?",[reason,now,auth.userId,tenantId,id]);auditAction='AGREEMENT_CANCELLED';
  }else throw issue('Unsupported agreement action',422);
  const after=await loadAgreement(context.env.DB,tenantId,id);await mirrorPartner(context.env.DB,tenantId,after.agreement);await audit(context.env.DB,tenantId,auth.userId,auditAction,id,{status:before.agreement.status,summary:before.summary},{status:after.agreement.status,summary:after.summary,reason:body._reason||body.reason||null});return json({updated:true,item:after,permissions:{canWrite:true,canFinalise:FINAL_ROLES.has(auth.role)}});
}catch(cause){return error(cause.message||'Agreement could not be updated',Number(cause.status||500));}}
